import { r, type SpecialismPack } from './shared'

const DATA_SIBLINGS = [
  'data-engineering',
  'data-analytics',
  'data-science',
  'artificial-intelligence',
  'machine-learning',
  'business-intelligence',
  'computer-vision',
  'robotics-software',
]

function siblings(except: string) {
  return DATA_SIBLINGS.filter((s) => s !== except)
}

const BCS_SOURCES = [
  'prospects_data_roles_uk',
  'bcs_chartered_it_professional',
  'national_careers_service_data',
  'uktech_job_profiles',
]

// ---------------------------------------------------------------------------
// 1) Data Engineering — BCS (~29 roles, no academic_research)
// ---------------------------------------------------------------------------
const DATA_ENGINEERING: SpecialismPack = {
  slug: 'data-engineering',
  label: 'Data Engineering',
  professionalBody: 'British Computer Society (BCS)',
  relatedBodies: ['Engineering Council', 'Institution of Engineering and Technology (IET)'],
  sources: BCS_SOURCES,
  siblingSlugs: siblings('data-engineering'),
  roles: [
    r('Graduate Data Engineer', 'entry_trainee', 'Entry UK role building batch and streaming pipelines, warehouse layers and data quality checks on graduate schemes or bootcamp-to-hire pathways.', { priority: 10, eligibilityNote: 'Immediate data-engineering entry — distinct from Data Analyst reporting and Data Scientist modelling roles.' }),
    r('Data Engineering Apprentice', 'entry_trainee', 'Level 4–6 digital/data apprenticeship supporting ETL jobs, cloud storage and pipeline monitoring under senior data engineers.', { priority: 20, eligibilityNote: 'Apprenticeship route into pipeline delivery; not BI dashboard or analytics insight work.' }),
    r('Junior ETL Developer (Graduate)', 'entry_trainee', 'Develops and maintains extract-transform-load jobs, schema mappings and reconciliation scripts under supervision.', { priority: 30, eligibilityNote: 'ETL-focused graduate entry — not generic software engineering or BI development.' }),
    r('Data Platform Trainee', 'entry_trainee', 'Supports lakehouse/warehouse platform operations, access controls and ingestion tooling on structured training programmes.', { priority: 40, eligibilityNote: 'Platform operations trainee — distinct from cloud infrastructure SRE unless data-platform scoped.' }),
    r('ETL Developer', 'junior', 'Owns scheduled batch pipelines, error handling and data lineage documentation for analytics and operational consumers.', { priority: 50, eligibilityNote: 'Junior pipeline delivery — not Business Intelligence semantic-layer or dashboard-first roles.' }),
    r('Data Pipeline Developer', 'junior', 'Builds reliable ingestion and transformation workflows across APIs, files and event streams with testable code.', { priority: 60, eligibilityNote: 'Pipeline engineering focus — not ML feature-store or model-serving engineering.' }),
    r('Junior Data Warehouse Developer', 'junior', 'Implements dimensional models, slowly changing dimensions and warehouse load patterns in cloud or on-prem platforms.', { priority: 70, eligibilityNote: 'Warehouse modelling at junior level — not BI Analyst requirements gathering.' }),
    r('Cloud Data Engineer (Junior)', 'junior', 'Deploys data services on AWS/Azure/GCP — storage, orchestration and IAM — for analytics and product data teams.', { priority: 80, eligibilityNote: 'Cloud data stack junior role — not general cloud platform engineering without data scope.' }),
    r('Database Developer (Data Engineering)', 'junior', 'Develops stored procedures, performance-tuned SQL and migration scripts supporting enterprise data platforms.', { priority: 90, eligibilityNote: 'Database development within data platforms — not application backend API engineering.' }),
    r('Data Engineer', 'practitioner', 'End-to-end ownership of pipeline design, data contracts, observability and platform standards for domain datasets.', { priority: 100, eligibilityNote: 'Core mid-level data engineering — distinct from Analytics Engineer (dbt/semantic) and Data Scientist.' }),
    r('Analytics Engineer (Data Platform)', 'practitioner', 'Transforms raw warehouse data into trusted marts using SQL/dbt, tests and documentation for downstream analysts.', { priority: 110, eligibilityNote: 'Analytics engineering on the data platform — not BI Developer dashboard tooling or DS modelling.' }),
    r('Data Integration Engineer', 'practitioner', 'Integrates SaaS, ERP and operational systems via APIs, CDC and event buses into the enterprise data estate.', { priority: 120, eligibilityNote: 'Integration engineering — not data-analytics insight delivery or AI/ML prototyping.' }),
    r('Streaming Data Engineer', 'practitioner', 'Designs Kafka/Kinesis/Flink-style real-time pipelines, windowing and late-data handling for operational analytics.', { priority: 130, eligibilityNote: 'Streaming specialist within data engineering — not generic backend microservices.' }),
    r('DataOps Engineer', 'practitioner', 'Automates pipeline CI/CD, environment promotion, data quality gates and cost/performance monitoring for data platforms.', { priority: 140, eligibilityNote: 'DataOps within data platforms — not organisation-wide DevOps unless data-estate scoped.' }),
    r('Senior Data Engineer', 'senior', 'Leads complex multi-source pipeline programmes, platform migrations and mentoring of junior data engineers.', { priority: 150, eligibilityNote: 'Senior pipeline/platform authority — not Head of Analytics or ML engineering lead.' }),
    r('Senior ETL Developer', 'senior', 'Architects high-volume batch patterns, idempotent loads and recovery strategies for critical finance/ops datasets.', { priority: 160, eligibilityNote: 'Senior ETL depth — not BI semantic modelling or computer-vision preprocessing pipelines.' }),
    r('Senior Data Platform Engineer', 'senior', 'Owns platform reliability, storage tiering, orchestration standards and golden-path templates for data teams.', { priority: 170, eligibilityNote: 'Senior platform engineering — distinct from enterprise solution architects outside data.' }),
    r('Senior Analytics Engineer', 'senior', 'Defines modelling standards, code review practices and trusted dataset contracts for analytics consumers.', { priority: 180, eligibilityNote: 'Senior analytics engineering — not Data Analyst team lead or Data Science lead.' }),
    r('Lead Data Engineer', 'lead_principal', 'Technical lead for a data engineering squad — roadmap, design reviews and cross-team data contract negotiation.', { priority: 190, eligibilityNote: 'Technical leadership of data pipelines — not people-manager unless combined role advertised.' }),
    r('Data Engineering Team Lead', 'lead_principal', 'Leads delivery of platform/pipeline workstreams, sprint planning and engineering quality for a data team.', { priority: 200, eligibilityNote: 'Delivery/technical lead — distinct from Data Engineering Manager HR line management.' }),
    r('Lead Analytics Engineer', 'lead_principal', 'Sets dbt/SQL engineering standards and coaches analysts/engineers on trusted transformation patterns.', { priority: 210, eligibilityNote: 'Lead analytics engineering — not BI Manager or Insights Manager.' }),
    r('Data Architect', 'architect_specialist', 'Defines enterprise data models, ingestion patterns, governance and target-state data platform architecture.', { priority: 220, eligibilityNote: 'Data architecture authority — not application/software solution architect unless data-centric.' }),
    r('Data Platform Architect', 'architect_specialist', 'Designs lakehouse/warehouse reference architectures, tooling choices and multi-cloud data platform strategy.', { priority: 230, eligibilityNote: 'Platform architecture — not AI/ML solution architecture or robotics systems architecture.' }),
    r('Enterprise Data Architect', 'architect_specialist', 'Aligns domain data products, master data and integration standards across business units at enterprise scale.', { priority: 240, eligibilityNote: 'Enterprise data design — distinct from BI programme architecture or CV pipeline architecture.' }),
    r('Data Engineering Manager', 'manager_head', 'Line manager for data engineers — hiring, performance, delivery governance and stakeholder management.', { priority: 250, eligibilityNote: 'People management of data engineering — not Analytics Manager or AI programme manager.' }),
    r('Head of Data Engineering', 'manager_head', 'Owns data platform/engineering function strategy, budget and senior hiring for pipeline and platform teams.', { priority: 260, eligibilityNote: 'Function head for data engineering — not Head of Data Science or Head of BI.' }),
    r('Data Platform Manager', 'manager_head', 'Manages platform reliability, vendor relationships and roadmap for shared data infrastructure services.', { priority: 270, eligibilityNote: 'Platform management — not IT infrastructure manager unless data-estate remit is explicit.' }),
    r('Director of Data Engineering', 'director_executive', 'Executive owner of enterprise data platform/engineering capability, investment and organisational data supply.', { priority: 280, eligibilityNote: 'Director-level data engineering — not Director of Analytics or Chief Data Officer unless combined.' }),
    r('VP Data Platform', 'director_executive', 'Senior technology executive accountable for cloud data platforms, engineering standards and multi-year data infrastructure strategy.', { priority: 290, eligibilityNote: 'VP data platform leadership — distinct from VP Analytics or VP AI/ML.' }),
  ],
}

// ---------------------------------------------------------------------------
// 2) Data Analytics — BCS (~29 roles, no academic_research)
// ---------------------------------------------------------------------------
const DATA_ANALYTICS: SpecialismPack = {
  slug: 'data-analytics',
  label: 'Data Analytics',
  professionalBody: 'British Computer Society (BCS)',
  relatedBodies: ['Royal Statistical Society (RSS)', 'Chartered Institute of Management Accountants (CIMA)'],
  sources: BCS_SOURCES,
  siblingSlugs: siblings('data-analytics'),
  roles: [
    r('Graduate Data Analyst', 'entry_trainee', 'Entry role producing management reports, KPI tracking and ad-hoc SQL analysis on graduate or conversion programmes.', { priority: 10, eligibilityNote: 'Immediate analytics entry — distinct from BI Developer (semantic layer) and Data Engineer (pipelines).' }),
    r('Data Analytics Apprentice', 'entry_trainee', 'Apprenticeship supporting dashboards, spreadsheet models and SQL queries for business teams under analyst supervision.', { priority: 20, eligibilityNote: 'Apprentice analyst route — not data-engineering apprenticeship or DS research pathway.' }),
    r('Junior Data Analyst (Graduate)', 'entry_trainee', 'Delivers recurring reports, data validation and stakeholder requests using SQL, Excel and visualisation tools.', { priority: 30, eligibilityNote: 'Graduate analyst — not Junior Data Scientist or BI Analyst (tooling-first) titles.' }),
    r('Analytics Graduate Trainee', 'entry_trainee', 'Rotational trainee across finance, marketing or operations analytics teams building core analyst toolkit.', { priority: 40, eligibilityNote: 'General analytics trainee — not ML graduate or AI engineer trainee.' }),
    r('Data Analyst', 'junior', 'Independent production of dashboards, metric definitions and investigative analysis for business questions.', { priority: 50, eligibilityNote: 'Core junior analyst — not Reporting Analyst (finance-led) or BI Developer (build-focused).' }),
    r('Reporting Analyst', 'junior', 'Owns scheduled management/finance reports, variance commentary and data quality checks for leadership packs.', { priority: 60, eligibilityNote: 'Reporting-centric analyst — distinct from Insights Analyst (exploratory) and BI Developer.' }),
    r('Insights Analyst', 'junior', 'Explores behavioural, commercial or product data to surface trends, cohorts and test readouts for stakeholders.', { priority: 70, eligibilityNote: 'Insight discovery — not Data Scientist statistical modelling or ML Engineer deployment.' }),
    r('SQL Data Analyst', 'junior', 'Heavy SQL-focused analyst extracting, joining and validating datasets for self-serve and embedded analytics.', { priority: 80, eligibilityNote: 'SQL analyst depth — not ETL Developer pipeline ownership or Analytics Engineer dbt ownership.' }),
    r('Web Analytics Analyst', 'junior', 'Tracks digital journeys, campaign attribution and conversion funnels using GA4/Adobe-style tooling.', { priority: 90, eligibilityNote: 'Digital/web analytics — not Marketing Data Analyst (CRM/offline) or BI semantic modeller.' }),
    r('Product Data Analyst', 'practitioner', 'Partners with product managers on experiment design, feature metrics and roadmap prioritisation using product telemetry.', { priority: 100, eligibilityNote: 'Product analytics — distinct from Product Data Scientist and generic BI Analyst.' }),
    r('Marketing Data Analyst', 'practitioner', 'Analyses campaign performance, customer segments and media mix using CRM and advertising platform data.', { priority: 110, eligibilityNote: 'Marketing analytics — not Insights Analyst (general) or BI Developer dashboard build.' }),
    r('Operations Data Analyst', 'practitioner', 'Optimises supply chain, service delivery or process KPIs with operational datasets and root-cause analysis.', { priority: 120, eligibilityNote: 'Operations-focused analyst — not Data Engineer or Robotics software analyst.' }),
    r('Financial Data Analyst', 'practitioner', 'Supports FP&A, revenue analysis and regulatory reporting packs with audited, controlled datasets.', { priority: 130, eligibilityNote: 'Finance analytics — not qualified accountant unless role explicitly hybrid.' }),
    r('Customer Analytics Analyst', 'practitioner', 'Models churn, lifetime value and segment behaviour for CRM and retention programmes.', { priority: 140, eligibilityNote: 'Customer analytics — not Data Scientist predictive-modelling lead or ML Engineer.' }),
    r('Senior Data Analyst', 'senior', 'Owns complex analytical workstreams, metric governance and coaches junior analysts on methods and quality.', { priority: 150, eligibilityNote: 'Senior analyst authority — not Senior Data Scientist or Senior BI Developer.' }),
    r('Senior Insights Analyst', 'senior', 'Leads deep-dive investigations, hypothesis testing and executive narrative for strategic decisions.', { priority: 160, eligibilityNote: 'Senior insights — distinct from Senior Reporting Analyst (pack production).' }),
    r('Senior Reporting Analyst', 'senior', 'Accountable for critical reporting cycles, controls and automation of leadership/finance report packs.', { priority: 170, eligibilityNote: 'Senior reporting — not BI Architect or Analytics Engineer.' }),
    r('Senior Product Data Analyst', 'senior', 'Sets product analytics standards, experiment governance and cross-squad metric frameworks.', { priority: 180, eligibilityNote: 'Senior product analytics — not Senior ML Engineer or AI Engineer.' }),
    r('Lead Data Analyst', 'lead_principal', 'Technical/process lead for an analyst squad — prioritisation, quality bar and stakeholder alignment.', { priority: 190, eligibilityNote: 'Analyst team technical lead — not Analytics Manager HR line unless dual hat.' }),
    r('Analytics Team Lead', 'lead_principal', 'Coordinates analyst delivery across domains, methods training and reusable analysis templates.', { priority: 200, eligibilityNote: 'Delivery lead for analysts — not Data Engineering Team Lead.' }),
    r('Lead Insights Analyst', 'lead_principal', 'Leads insight programmes, advanced analysis approaches and knowledge sharing across analyst community.', { priority: 210, eligibilityNote: 'Lead insights — not Lead Data Scientist or BI Team Lead.' }),
    r('Analytics Solution Architect', 'architect_specialist', 'Designs self-serve analytics architecture — metric stores, semantic layers and analyst tooling ecosystems.', { priority: 220, eligibilityNote: 'Analytics architecture — not Data Platform Architect or Enterprise BI Architect alone.' }),
    r('Data Analytics Architect', 'architect_specialist', 'Defines target analytics operating model, data product boundaries and analyst/engineer interaction patterns.', { priority: 230, eligibilityNote: 'Analytics function architecture — distinct from Data Architect (pipelines/warehouse).' }),
    r('Self-Service Analytics Architect', 'architect_specialist', 'Designs governed self-serve layers, certification workflows and analyst enablement on warehouse/lakehouse data.', { priority: 240, eligibilityNote: 'Self-serve design — not Computer Vision pipeline architect or AI solution architect.' }),
    r('Analytics Manager', 'manager_head', 'Line manager for data analysts — capacity planning, career development and analytics SLA ownership.', { priority: 250, eligibilityNote: 'People manager for analysts — not BI Manager (developer team) or Data Science manager.' }),
    r('Head of Data Analytics', 'manager_head', 'Leads analytics function strategy, hiring and stakeholder engagement across business domains.', { priority: 260, eligibilityNote: 'Head of analytics — not Head of BI or Head of Data Science.' }),
    r('Insights Manager', 'manager_head', 'Manages insights/analyst teams focused on exploratory and strategic analysis programmes.', { priority: 270, eligibilityNote: 'Insights management — not Insights Engineer (data engineering) or AI programme manager.' }),
    r('Director of Analytics', 'director_executive', 'Executive leadership of enterprise analytics capability, investment and analytics-driven decision culture.', { priority: 280, eligibilityNote: 'Director analytics — distinct from Director of BI or Director of Data Engineering.' }),
    r('Chief Analytics Officer', 'director_executive', 'C-suite or near-C-suite owner of analytics strategy, advanced analytics portfolio and organisational data literacy.', { priority: 290, eligibilityNote: 'CAO-style leadership — not Chief Data Officer (platform) or Chief AI Officer.' }),
  ],
}

// ---------------------------------------------------------------------------
// 3) Data Science — RSS (~27 industry + 3 academic_research = 30)
// ---------------------------------------------------------------------------
const DATA_SCIENCE: SpecialismPack = {
  slug: 'data-science',
  label: 'Data Science',
  professionalBody: 'Royal Statistical Society (RSS)',
  relatedBodies: ['British Computer Society (BCS)', 'Institute of Mathematics and its Applications (IMA)'],
  sources: ['prospects_data_scientist', 'rss_data_science', 'bcs_ai_ml_guidance', 'national_careers_service_data'],
  siblingSlugs: siblings('data-science'),
  roles: [
    r('Graduate Data Scientist', 'entry_trainee', 'Entry role supporting experiments, feature analysis and prototype models on graduate schemes with stats/ML coursework.', { priority: 10, eligibilityNote: 'Graduate DS entry — distinct from Graduate Data Analyst (reporting) and ML Engineer (deployment).' }),
    r('Data Science Apprentice', 'entry_trainee', 'Higher apprenticeship applying Python/R, basic modelling and notebook workflows under senior data scientists.', { priority: 20, eligibilityNote: 'Apprentice DS — not data-engineering apprentice or BI developer apprentice.' }),
    r('Junior Data Scientist (Graduate)', 'entry_trainee', 'Builds exploratory models, evaluates metrics and documents findings for product or risk use cases.', { priority: 30, eligibilityNote: 'Junior DS modelling — not Junior AI Engineer (LLM systems) or Statistical Analyst (reporting).' }),
    r('Statistical Analyst (Junior)', 'junior', 'Applies regression, hypothesis tests and survey methods to business or public-sector research questions.', { priority: 40, eligibilityNote: 'Statistics-heavy junior — not Reporting Analyst or generic Data Analyst.' }),
    r('Junior Data Scientist', 'junior', 'Develops predictive models, validates assumptions and partners with engineers on feature pipelines.', { priority: 50, eligibilityNote: 'Junior DS — not ML Engineer (MLOps/deployment) or BI Analyst.' }),
    r('Quantitative Analyst (Junior)', 'junior', 'Supports pricing, risk or trading analytics with statistical models under senior quant supervision.', { priority: 60, eligibilityNote: 'Quant junior in DS pack — not pure finance quant developer unless modelling-focused.' }),
    r('Data Science Associate', 'junior', 'Consultancy-style associate delivering client modelling, evaluation and insight decks on project teams.', { priority: 70, eligibilityNote: 'Associate DS delivery — not Data Analytics Associate (SQL/dashboards).' }),
    r('Applied Data Scientist', 'practitioner', 'Ships production-minded models with experimentation, monitoring hooks and stakeholder-ready evaluation.', { priority: 80, eligibilityNote: 'Applied DS — distinct from Research Scientist (publication) and ML Engineer (infra).' }),
    r('Data Scientist', 'practitioner', 'End-to-end modelling from problem framing through validation, deployment handoff and iteration.', { priority: 90, eligibilityNote: 'Core mid-level DS — not Data Analyst insight role or AI Engineer agent systems.' }),
    r('Statistical Modeller', 'practitioner', 'Builds GLM, survival, Bayesian or econometric models for insurance, health or policy domains.', { priority: 100, eligibilityNote: 'Statistical modelling — not Computer Vision engineer or Robotics perception scientist.' }),
    r('Predictive Modeller', 'practitioner', 'Focuses on forecasting, classification and uplift models with rigorous back-testing and drift awareness.', { priority: 110, eligibilityNote: 'Predictive modelling — not BI predictive planning tools administrator.' }),
    r('Senior Data Scientist', 'senior', 'Leads complex modelling programmes, mentors juniors and sets validation/governance standards.', { priority: 120, eligibilityNote: 'Senior DS — not Senior ML Engineer or Senior AI Engineer.' }),
    r('Senior Applied Data Scientist', 'senior', 'Owns high-impact model lifecycles in product with A/B testing, causal methods and exec communication.', { priority: 130, eligibilityNote: 'Senior applied DS — not Senior Data Analyst or BI Architect.' }),
    r('Senior Statistical Modeller', 'senior', 'Authority on advanced inference, model risk and regulatory statistical methods in regulated sectors.', { priority: 140, eligibilityNote: 'Senior stats depth — not academic Research Fellow unless explicitly research post.' }),
    r('Principal Data Scientist', 'senior', 'Org-wide modelling standards, method selection and cross-domain scientific leadership.', { priority: 150, eligibilityNote: 'Principal DS — distinct from Principal ML Engineer or AI Research Scientist.' }),
    r('Lead Data Scientist', 'lead_principal', 'Technical lead for a data science squad — roadmap, peer review and model risk alignment.', { priority: 160, eligibilityNote: 'DS technical lead — not Analytics Team Lead or ML Team Lead.' }),
    r('Data Science Team Lead', 'lead_principal', 'Leads modelling workstreams, sprint planning and stakeholder science communication for DS teams.', { priority: 170, eligibilityNote: 'DS delivery lead — not Data Science Manager unless people-management combined.' }),
    r('Lead Statistical Modeller', 'lead_principal', 'Sets statistical methodology standards and coaches modellers on inference and documentation.', { priority: 180, eligibilityNote: 'Lead stats — not Lead Data Analyst or BI Team Lead.' }),
    r('Data Science Architect', 'architect_specialist', 'Designs model development platforms, feature stores, experiment systems and DS operating models.', { priority: 190, eligibilityNote: 'DS architecture — not Data Platform Architect (pipelines) or AI Solution Architect.' }),
    r('Analytics Science Architect', 'architect_specialist', 'Bridges analytics and science — metric design, causal inference frameworks and model governance architecture.', { priority: 200, eligibilityNote: 'Science/analytics architecture — distinct from Enterprise Data Architect.' }),
    r('Modelling Platform Architect', 'architect_specialist', 'Defines MLOps-adjacent science platforms, notebook governance and reproducible research tooling.', { priority: 210, eligibilityNote: 'Modelling platform — not ML Infrastructure Architect (pure eng) unless hybrid.' }),
    r('Data Science Manager', 'manager_head', 'Line manager for data scientists — hiring, performance and portfolio prioritisation.', { priority: 220, eligibilityNote: 'People manager for DS — not Analytics Manager or AI Manager.' }),
    r('Head of Data Science', 'manager_head', 'Owns DS function strategy, ethics/governance and senior science hiring across the organisation.', { priority: 230, eligibilityNote: 'Head of DS — not Head of ML or Head of AI unless explicitly combined remit.' }),
    r('Head of Advanced Analytics', 'manager_head', 'Leads advanced analytics/science teams spanning experimentation, modelling and decision science.', { priority: 240, eligibilityNote: 'Advanced analytics leadership — not Head of BI or Head of Data Analytics alone.' }),
    r('Director of Data Science', 'director_executive', 'Executive owner of enterprise data science capability, investment and model-risk oversight.', { priority: 250, eligibilityNote: 'Director DS — distinct from Director of AI/ML or Director of Analytics.' }),
    r('Chief Data Scientist', 'director_executive', 'Top scientific leader setting enterprise modelling strategy, research partnerships and science culture.', { priority: 260, eligibilityNote: 'Chief Data Scientist — not Chief AI Officer (broader AI product/strategy).' }),
    r('Research Scientist (Data Science)', 'academic_research', 'Conducts publishable research in statistics, ML theory or applied data science in industry R&D or public labs.', { priority: 270, isResearchRole: true, isAcademicRole: false, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'Industry/public research scientist — not product Data Scientist or academic Lecturer post.' }),
    r('Research Fellow (Statistics & Data Science)', 'academic_research', 'Postdoctoral or fixed-term fellow advancing statistical/ML methods with grant-funded research outputs.', { priority: 280, isResearchRole: true, isAcademicRole: false, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'Research fellowship — not Senior Statistical Modeller in industry.' }),
    r('Lecturer in Data Science', 'academic_research', 'University teaching and research in data science, statistics and ML with PhD and publication expectations.', { priority: 290, isResearchRole: false, isAcademicRole: true, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'Academic lectureship — not industry Data Science Manager or training-only instructor.' }),
  ],
}

// ---------------------------------------------------------------------------
// 4) Artificial Intelligence — BCS (~27 industry + 3 academic_research = 30)
// ---------------------------------------------------------------------------
const ARTIFICIAL_INTELLIGENCE: SpecialismPack = {
  slug: 'artificial-intelligence',
  label: 'Artificial Intelligence',
  professionalBody: 'British Computer Society (BCS)',
  relatedBodies: ['Royal Statistical Society (RSS)', 'Alan Turing Institute'],
  sources: ['prospects_ai_engineer', 'bcs_ai_ethics', 'uk_ai_safety_institute', 'national_careers_service_data'],
  siblingSlugs: siblings('artificial-intelligence'),
  roles: [
    r('Graduate AI Engineer', 'entry_trainee', 'Entry role supporting LLM integrations, prompt workflows and AI feature prototypes on graduate programmes.', { priority: 10, eligibilityNote: 'AI engineering entry — distinct from ML Engineer (model training) and Data Scientist (stats-led).' }),
    r('AI Engineering Apprentice', 'entry_trainee', 'Apprenticeship assisting API integrations, evaluation harnesses and guardrail testing for AI products.', { priority: 20, eligibilityNote: 'AI apprentice — not data-analytics apprentice or robotics apprentice.' }),
    r('Junior AI Engineer (Graduate)', 'entry_trainee', 'Builds agent tools, RAG pipelines and inference endpoints under senior AI engineers.', { priority: 30, eligibilityNote: 'Junior AI eng — not Junior ML Engineer (training pipelines) or BI Developer.' }),
    r('AI Solutions Trainee', 'entry_trainee', 'Trainee on consultancy AI programmes configuring copilots, knowledge bases and safety checks.', { priority: 40, eligibilityNote: 'AI solutions trainee — not generic software graduate or CV engineer trainee.' }),
    r('Junior AI Engineer', 'junior', 'Implements LLM applications, orchestration frameworks and monitoring for production AI features.', { priority: 50, eligibilityNote: 'Junior AI — not Machine Learning Engineer unless training/deployment-heavy advert.' }),
    r('Generative AI Engineer (Junior)', 'junior', 'Focuses on generative models, fine-tuning workflows and content-safety filters in product teams.', { priority: 60, eligibilityNote: 'GenAI junior — distinct from Computer Vision engineer and Data Scientist.' }),
    r('AI Integration Engineer (Junior)', 'junior', 'Integrates third-party and open models into enterprise apps with auth, logging and cost controls.', { priority: 70, eligibilityNote: 'Integration-focused AI — not Data Integration Engineer (ETL).' }),
    r('Prompt Engineer (Junior)', 'junior', 'Designs, tests and documents prompts/eval suites for reliable LLM behaviour in workflows.', { priority: 80, eligibilityNote: 'Prompt engineering — not technical writer unless dev-test remit is minimal.' }),
    r('AI Engineer', 'practitioner', 'Owns AI feature delivery — model selection, evaluation, guardrails and backend inference design.', { priority: 90, eligibilityNote: 'Core AI engineer — not ML Engineer (training infra) or AI Research Scientist.' }),
    r('LLM Application Engineer', 'practitioner', 'Builds production LLM apps with retrieval, tool use, caching and latency/cost optimisation.', { priority: 100, eligibilityNote: 'LLM apps — not NLP Research Scientist or generic backend engineer.' }),
    r('AI Product Engineer', 'practitioner', 'Partners with PM/design to ship AI-powered UX with offline/online eval and rollout controls.', { priority: 110, eligibilityNote: 'AI product engineering — not Product Data Analyst or BI Developer.' }),
    r('Conversational AI Engineer', 'practitioner', 'Develops chat/voice agents, dialogue management and human-handoff patterns for service automation.', { priority: 120, eligibilityNote: 'Conversational AI — not Robotics dialogue systems unless hardware-robot scoped.' }),
    r('Senior AI Engineer', 'senior', 'Leads complex AI programmes, red-teaming, eval frameworks and mentoring of junior AI engineers.', { priority: 130, eligibilityNote: 'Senior AI — not Senior ML Engineer or Senior Data Scientist.' }),
    r('Senior Generative AI Engineer', 'senior', 'Owns genAI platform patterns, fine-tuning strategy and enterprise policy alignment.', { priority: 140, eligibilityNote: 'Senior genAI — not Computer Vision senior or BI Architect.' }),
    r('Senior LLM Engineer', 'senior', 'Authority on LLM serving, routing, observability and multi-model orchestration at scale.', { priority: 150, eligibilityNote: 'Senior LLM — not ML Infrastructure Architect unless training platform owned.' }),
    r('Principal AI Engineer', 'senior', 'Org-wide AI engineering standards, reference architectures and cross-squad technical leadership.', { priority: 160, eligibilityNote: 'Principal AI — distinct from Principal ML Engineer and AI Research Scientist.' }),
    r('Lead AI Engineer', 'lead_principal', 'Technical lead for AI squad — roadmap, design reviews and stakeholder AI risk communication.', { priority: 170, eligibilityNote: 'AI technical lead — not ML Team Lead unless combined remit advertised.' }),
    r('AI Engineering Team Lead', 'lead_principal', 'Leads AI delivery workstreams, sprint quality and reusable AI component libraries.', { priority: 180, eligibilityNote: 'AI delivery lead — not AI Manager people-management unless dual role.' }),
    r('Lead Generative AI Engineer', 'lead_principal', 'Sets genAI engineering practices, eval gates and platform adoption across product teams.', { priority: 190, eligibilityNote: 'Lead genAI — not Lead Data Scientist or Robotics software lead.' }),
    r('AI Solution Architect', 'architect_specialist', 'Designs enterprise AI reference architectures, vendor/model strategy and integration patterns.', { priority: 200, eligibilityNote: 'AI solution architecture — not Data Architect or Enterprise BI Architect.' }),
    r('Generative AI Architect', 'architect_specialist', 'Defines genAI platform topology, data boundaries, safety layers and deployment models.', { priority: 210, eligibilityNote: 'GenAI architecture — not ML Platform Architect (training) unless hybrid.' }),
    r('Enterprise AI Architect', 'architect_specialist', 'Aligns AI capabilities across domains with governance, cost and responsible-AI controls.', { priority: 220, eligibilityNote: 'Enterprise AI — not Computer Vision Architect or Robotics systems architect.' }),
    r('AI Engineering Manager', 'manager_head', 'Line manager for AI engineers — hiring, delivery governance and AI product partnership.', { priority: 230, eligibilityNote: 'People manager AI eng — not Data Science Manager or ML Manager.' }),
    r('Head of AI Engineering', 'manager_head', 'Owns AI engineering function, platform choices and senior hiring for AI product delivery.', { priority: 240, eligibilityNote: 'Head of AI engineering — not Head of AI Research or Chief AI Officer alone.' }),
    r('Head of Applied AI', 'manager_head', 'Leads applied AI teams shipping customer-facing AI with eval and safety programme ownership.', { priority: 250, eligibilityNote: 'Applied AI leadership — not Head of BI or Head of Analytics.' }),
    r('Director of AI Engineering', 'director_executive', 'Executive leadership of AI engineering capability, investment and enterprise AI rollout.', { priority: 260, eligibilityNote: 'Director AI eng — distinct from Director of ML or Director of Data Science.' }),
    r('Chief AI Officer', 'director_executive', 'C-suite or near-C-suite owner of AI strategy, responsible AI and AI product portfolio.', { priority: 270, eligibilityNote: 'CAIO — broader than AI Engineering Manager; may span research, product and policy.' }),
    r('AI Research Scientist', 'academic_research', 'Conducts fundamental or applied AI research — novel models, agents or safety — with publication outputs.', { priority: 280, isResearchRole: true, isAcademicRole: false, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'AI research — not production AI Engineer or ML Engineer deployment role.' }),
    r('Research Fellow (Artificial Intelligence)', 'academic_research', 'Fixed-term postdoc advancing AI methods in university or institute settings with grant deliverables.', { priority: 290, isResearchRole: true, isAcademicRole: false, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'AI fellowship — not Senior AI Engineer in industry R&D without research output.' }),
    r('Lecturer in Artificial Intelligence', 'academic_research', 'University teaching and research in AI/ML with PhD, publications and student supervision.', { priority: 300, isResearchRole: false, isAcademicRole: true, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'Academic AI lectureship — not corporate AI trainer or prompt-engineering contractor.' }),
  ],
}

// ---------------------------------------------------------------------------
// 5) Machine Learning — BCS (~27 industry + 3 academic_research = 30)
// ---------------------------------------------------------------------------
const MACHINE_LEARNING: SpecialismPack = {
  slug: 'machine-learning',
  label: 'Machine Learning',
  professionalBody: 'British Computer Society (BCS)',
  relatedBodies: ['Royal Statistical Society (RSS)', 'Institute of Physics (IOP)'],
  sources: ['prospects_ml_engineer', 'bcs_ai_ml_guidance', 'mlops_community_uk', 'national_careers_service_data'],
  siblingSlugs: siblings('machine-learning'),
  roles: [
    r('Graduate ML Engineer', 'entry_trainee', 'Entry role supporting training pipelines, experiment tracking and model packaging on graduate schemes.', { priority: 10, eligibilityNote: 'ML engineering entry — distinct from Graduate AI Engineer (LLM apps) and Graduate Data Scientist.' }),
    r('Machine Learning Apprentice', 'entry_trainee', 'Apprenticeship assisting dataset prep, baseline models and deployment scripts under ML engineers.', { priority: 20, eligibilityNote: 'ML apprentice — not AI apprentice (LLM) or data-engineering apprentice.' }),
    r('Junior ML Engineer (Graduate)', 'entry_trainee', 'Builds training jobs, feature pipelines and model evaluation notebooks for supervised learning use cases.', { priority: 30, eligibilityNote: 'Junior ML eng — not Junior AI Engineer or Statistical Analyst.' }),
    r('MLOps Trainee', 'entry_trainee', 'Trainee supporting model registry, CI/CD for ML and monitoring dashboards on structured programmes.', { priority: 40, eligibilityNote: 'MLOps trainee — not DevOps trainee unless ML-platform scoped.' }),
    r('Junior Machine Learning Engineer', 'junior', 'Implements model training, hyperparameter workflows and batch/online inference services.', { priority: 50, eligibilityNote: 'Junior ML — not Data Scientist (problem framing) or BI Developer.' }),
    r('ML Platform Engineer (Junior)', 'junior', 'Maintains shared ML platforms — schedulers, GPUs, experiment stores and deployment templates.', { priority: 60, eligibilityNote: 'Junior ML platform — not Cloud Data Engineer or generic SRE.' }),
    r('NLP Engineer (Junior)', 'junior', 'Builds text classification, embedding and retrieval models with standard NLP tooling.', { priority: 70, eligibilityNote: 'NLP engineering — not Prompt Engineer (LLM-only) or NLP Research Scientist.' }),
    r('Recommendation Systems Engineer (Junior)', 'junior', 'Supports collaborative filtering, ranking features and A/B hooks for personalisation products.', { priority: 80, eligibilityNote: 'Recsys junior — not Marketing Data Analyst or Product Data Analyst alone.' }),
    r('Machine Learning Engineer', 'practitioner', 'Owns model lifecycle from training through deployment, monitoring and retraining triggers.', { priority: 90, eligibilityNote: 'Core ML engineer — not AI Engineer (LLM orchestration) or Data Scientist.' }),
    r('MLOps Engineer', 'practitioner', 'Automates ML pipelines, model promotion gates, drift detection and reproducible training infra.', { priority: 100, eligibilityNote: 'MLOps — not DataOps Engineer (batch ETL) unless ML-platform unified.' }),
    r('Deep Learning Engineer', 'practitioner', 'Develops neural networks for tabular, text or multimodal problems with GPU training optimisation.', { priority: 110, eligibilityNote: 'Deep learning eng — not Computer Vision Engineer unless vision-only advert.' }),
    r('ML Inference Engineer', 'practitioner', 'Optimises model serving latency, batching, hardware acceleration and scalable inference APIs.', { priority: 120, eligibilityNote: 'Inference engineering — not backend API engineer without ML serving remit.' }),
    r('Senior Machine Learning Engineer', 'senior', 'Leads high-scale ML systems, cost/performance trade-offs and mentors junior ML engineers.', { priority: 130, eligibilityNote: 'Senior ML — not Senior AI Engineer or Senior Data Scientist.' }),
    r('Senior MLOps Engineer', 'senior', 'Owns enterprise MLOps standards, incident response for models and platform reliability.', { priority: 140, eligibilityNote: 'Senior MLOps — not Senior Data Platform Engineer unless ML platform owned.' }),
    r('Senior Deep Learning Engineer', 'senior', 'Authority on architecture search, distributed training and production DL quality bars.', { priority: 150, eligibilityNote: 'Senior DL — not Senior Computer Vision Engineer unless vision-specific role.' }),
    r('Principal ML Engineer', 'senior', 'Org-wide ML engineering patterns, tech selection and cross-team ML platform leadership.', { priority: 160, eligibilityNote: 'Principal ML — distinct from Principal AI Engineer and ML Research Scientist.' }),
    r('Lead Machine Learning Engineer', 'lead_principal', 'Technical lead for ML squad — model risk alignment, design reviews and delivery prioritisation.', { priority: 170, eligibilityNote: 'ML technical lead — not AI Engineering Team Lead unless combined.' }),
    r('ML Engineering Team Lead', 'lead_principal', 'Leads ML delivery workstreams, reusable training/serving templates and squad quality.', { priority: 180, eligibilityNote: 'ML delivery lead — not ML Engineering Manager HR line unless dual hat.' }),
    r('Lead MLOps Engineer', 'lead_principal', 'Sets MLOps practices, deployment gates and observability standards across ML teams.', { priority: 190, eligibilityNote: 'Lead MLOps — not Lead Data Engineer or DevOps lead.' }),
    r('ML Platform Architect', 'architect_specialist', 'Designs training/serving platforms, feature stores and model governance architecture.', { priority: 200, eligibilityNote: 'ML platform architecture — not Data Platform Architect (warehouse) alone.' }),
    r('MLOps Architect', 'architect_specialist', 'Defines CI/CD for models, environment strategy and operational model-risk controls.', { priority: 210, eligibilityNote: 'MLOps architecture — not AI Solution Architect (LLM product).' }),
    r('Machine Learning Architect', 'architect_specialist', 'Enterprise ML reference designs, tooling roadmap and cross-domain model integration patterns.', { priority: 220, eligibilityNote: 'ML architect — not Computer Vision Architect or Robotics software architect.' }),
    r('ML Engineering Manager', 'manager_head', 'Line manager for ML engineers — hiring, portfolio and ML platform partnership.', { priority: 230, eligibilityNote: 'People manager ML — not Data Science Manager or AI Engineering Manager.' }),
    r('Head of Machine Learning Engineering', 'manager_head', 'Owns ML engineering function, platform investment and senior ML hiring.', { priority: 240, eligibilityNote: 'Head of ML eng — not Head of AI or Head of Data Science.' }),
    r('Head of MLOps', 'manager_head', 'Leads MLOps/platform operations teams supporting model deployment at scale.', { priority: 250, eligibilityNote: 'Head of MLOps — not Head of Data Engineering or Head of DevOps.' }),
    r('Director of Machine Learning', 'director_executive', 'Executive owner of ML engineering capability, model-risk governance and ML investment.', { priority: 260, eligibilityNote: 'Director ML — distinct from Director of AI Engineering or Director of Data Science.' }),
    r('VP Machine Learning Engineering', 'director_executive', 'Senior executive accountable for ML platforms, engineering standards and enterprise ML rollout.', { priority: 270, eligibilityNote: 'VP ML eng — not VP AI or Chief Data Scientist.' }),
    r('ML Research Scientist', 'academic_research', 'Conducts ML method research — optimisation, generalisation or systems — with publications/patents.', { priority: 280, isResearchRole: true, isAcademicRole: false, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'ML research — not production Machine Learning Engineer or MLOps Engineer.' }),
    r('Research Fellow (Machine Learning)', 'academic_research', 'Postdoctoral fellow advancing ML theory or systems in university/industry lab settings.', { priority: 290, isResearchRole: true, isAcademicRole: false, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'ML fellowship — not Senior ML Engineer in product team.' }),
    r('Lecturer in Machine Learning', 'academic_research', 'University teaching and research in machine learning with PhD and peer-reviewed output expectations.', { priority: 300, isResearchRole: false, isAcademicRole: true, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'Academic ML lectureship — not corporate ML trainer or bootcamp instructor.' }),
  ],
}

// ---------------------------------------------------------------------------
// 6) Business Intelligence — BCS (~29 roles, no academic_research)
// ---------------------------------------------------------------------------
const BUSINESS_INTELLIGENCE: SpecialismPack = {
  slug: 'business-intelligence',
  label: 'Business Intelligence',
  professionalBody: 'British Computer Society (BCS)',
  relatedBodies: ['Chartered Institute of Management Accountants (CIMA)', 'Royal Statistical Society (RSS)'],
  sources: ['prospects_bi_analyst', 'bcs_data_professional', 'microsoft_power_bi_uk', 'tableau_public_sector_uk'],
  siblingSlugs: siblings('business-intelligence'),
  roles: [
    r('Graduate BI Developer', 'entry_trainee', 'Entry role building dashboards, semantic models and SQL datasets on BI graduate schemes.', { priority: 10, eligibilityNote: 'BI developer entry — distinct from Graduate Data Analyst (analysis-first) and Data Engineer.' }),
    r('Business Intelligence Apprentice', 'entry_trainee', 'Apprenticeship supporting Power BI/Tableau reports, data models and user training under BI developers.', { priority: 20, eligibilityNote: 'BI apprentice — not data-analytics apprentice or ML apprentice.' }),
    r('Junior BI Analyst (Graduate)', 'entry_trainee', 'Translates business requirements into KPI definitions, prototype dashboards and UAT with stakeholders.', { priority: 30, eligibilityNote: 'Junior BI analyst — not Junior Data Analyst (SQL insight) or Reporting Analyst alone.' }),
    r('BI Reporting Trainee', 'entry_trainee', 'Trainee producing governed report packs, drill-through dashboards and documentation for business users.', { priority: 40, eligibilityNote: 'BI reporting trainee — not web analytics or financial accountant trainee.' }),
    r('BI Developer', 'junior', 'Develops enterprise dashboards, DAX/MDX or equivalent and reusable data models in BI platforms.', { priority: 50, eligibilityNote: 'Core BI developer — not ETL Developer or Analytics Engineer (dbt).' }),
    r('Power BI Developer', 'junior', 'Specialises in Power BI datasets, row-level security, deployment pipelines and performance tuning.', { priority: 60, eligibilityNote: 'Power BI focus — not generic Data Analyst or AI Engineer.' }),
    r('Tableau Developer', 'junior', 'Builds Tableau workbooks, extracts, governance and embedded analytics for departments.', { priority: 70, eligibilityNote: 'Tableau developer — not Insights Analyst (exploratory) or ML Engineer.' }),
    r('BI Analyst', 'junior', 'Bridges business and BI tooling — requirements, acceptance testing and report catalogue ownership.', { priority: 80, eligibilityNote: 'BI analyst — distinct from Data Analyst (analysis delivery) and BI Developer (build-heavy).' }),
    r('Semantic Modeller (Junior)', 'junior', 'Implements star/snowflake semantic layers, measures and hierarchies for self-serve BI.', { priority: 90, eligibilityNote: 'Semantic modelling — not Data Warehouse Developer (ELT pipelines).' }),
    r('Senior BI Developer', 'practitioner', 'Owns complex BI programmes, performance optimisation and release governance across environments.', { priority: 100, eligibilityNote: 'Mid/senior BI build — not Senior Data Analyst or Analytics Engineer.' }),
    r('BI Report Developer', 'practitioner', 'Delivers executive and regulatory report templates with drill-down, subscriptions and audit trails.', { priority: 110, eligibilityNote: 'Report developer — not Reporting Analyst (commentary/analysis-led).' }),
    r('Embedded Analytics Developer', 'practitioner', 'Integrates BI visuals and APIs into SaaS products with multi-tenant security and theming.', { priority: 120, eligibilityNote: 'Embedded BI — not frontend product engineer unless BI SDK primary.' }),
    r('BI Data Modeller', 'practitioner', 'Designs enterprise semantic models, conformed dimensions and certified dataset standards.', { priority: 130, eligibilityNote: 'BI modelling — not Enterprise Data Architect (platform-wide).' }),
    r('Lead BI Developer', 'senior', 'Leads BI squads, code review standards and platform best practices for large report estates.', { priority: 140, eligibilityNote: 'Senior BI lead dev — not Lead Data Analyst or AI Engineer.' }),
    r('Senior Power BI Developer', 'senior', 'Authority on Power BI enterprise deployment, XMLA, incremental refresh and capacity planning.', { priority: 150, eligibilityNote: 'Senior Power BI — not Senior Reporting Analyst or Data Engineer.' }),
    r('Senior Tableau Developer', 'senior', 'Owns Tableau Server/Cloud governance, extract optimisation and Centre of Excellence patterns.', { priority: 160, eligibilityNote: 'Senior Tableau — not Senior Insights Analyst or ML Engineer.' }),
    r('Senior BI Analyst', 'senior', 'Leads requirements discovery, backlog prioritisation and BI quality for business domains.', { priority: 170, eligibilityNote: 'Senior BI analyst — not Senior Data Analyst (analysis-first).' }),
    r('BI Team Lead', 'lead_principal', 'Technical/delivery lead for BI developers — sprint planning, releases and stakeholder demos.', { priority: 180, eligibilityNote: 'BI team lead — not Analytics Team Lead or Data Engineering Team Lead.' }),
    r('Lead Semantic Modeller', 'lead_principal', 'Sets semantic-layer standards, certification workflows and cross-domain measure dictionaries.', { priority: 190, eligibilityNote: 'Lead semantic modelling — not Lead Analytics Engineer (dbt).' }),
    r('Lead Power BI Engineer', 'lead_principal', 'Leads Power BI platform adoption, shared datasets and developer coaching.', { priority: 200, eligibilityNote: 'Lead Power BI — not Lead AI Engineer or Robotics software lead.' }),
    r('Enterprise BI Architect', 'architect_specialist', 'Designs enterprise BI topology, tool strategy, data governance and certified reporting architecture.', { priority: 210, eligibilityNote: 'Enterprise BI architecture — not Data Platform Architect or AI Solution Architect.' }),
    r('Analytics & BI Architect', 'architect_specialist', 'Aligns BI semantic layers with warehouse marts and self-serve analytics boundaries.', { priority: 220, eligibilityNote: 'BI/analytics architecture — distinct from Data Analytics Architect (analyst ops).' }),
    r('Microsoft BI Architect', 'architect_specialist', 'Reference architectures for Microsoft fabric/power platform BI, security and lifecycle management.', { priority: 230, eligibilityNote: 'Microsoft BI — not cloud infrastructure architect unless BI platform scoped.' }),
    r('BI Manager', 'manager_head', 'Line manager for BI developers/analysts — capacity, hiring and report SLA ownership.', { priority: 240, eligibilityNote: 'BI people manager — not Analytics Manager (analyst team) or Data Science Manager.' }),
    r('Head of Business Intelligence', 'manager_head', 'Owns BI function strategy, tooling roadmap and senior BI hiring.', { priority: 250, eligibilityNote: 'Head of BI — not Head of Data Analytics or Head of ML.' }),
    r('Head of Reporting & BI', 'manager_head', 'Leads combined reporting and BI teams for finance/operations leadership packs.', { priority: 260, eligibilityNote: 'Reporting/BI head — not Head of Data Engineering.' }),
    r('Director of Business Intelligence', 'director_executive', 'Executive owner of enterprise BI capability, investment and data-driven reporting culture.', { priority: 270, eligibilityNote: 'Director BI — distinct from Director of Analytics or Director of Data Engineering.' }),
    r('Chief BI Officer', 'director_executive', 'Senior leader accountable for enterprise reporting, BI platforms and executive information strategy.', { priority: 280, eligibilityNote: 'CBO-style BI leadership — not Chief Data Officer (platform) or CAIO.' }),
    r('VP Business Intelligence', 'director_executive', 'VP-level ownership of BI programmes, vendor relationships and global report estate standards.', { priority: 290, eligibilityNote: 'VP BI — not VP Analytics or VP AI/ML.' }),
  ],
}

// ---------------------------------------------------------------------------
// 7) Computer Vision — BCS (~27 industry + 3 academic_research = 30)
// ---------------------------------------------------------------------------
const COMPUTER_VISION: SpecialismPack = {
  slug: 'computer-vision',
  label: 'Computer Vision',
  professionalBody: 'British Computer Society (BCS)',
  relatedBodies: ['Institution of Engineering and Technology (IET)', 'Royal Academy of Engineering'],
  sources: ['prospects_software_engineer', 'bcs_ai_ml_guidance', 'uk_robotics_computer_vision', 'opencv_careers'],
  siblingSlugs: siblings('computer-vision'),
  roles: [
    r('Graduate Computer Vision Engineer', 'entry_trainee', 'Entry role supporting image datasets, baseline detectors and edge deployment prototypes on graduate schemes.', { priority: 10, eligibilityNote: 'CV graduate entry — distinct from Graduate ML Engineer (general) and Graduate AI Engineer (LLM).' }),
    r('Computer Vision Apprentice', 'entry_trainee', 'Apprenticeship labelling pipelines, camera calibration assists and model evaluation under CV engineers.', { priority: 20, eligibilityNote: 'CV apprentice — not robotics hardware apprentice or data-analytics apprentice.' }),
    r('Junior CV Engineer (Graduate)', 'entry_trainee', 'Implements classification/detection models, augmentation pipelines and inference benchmarks.', { priority: 30, eligibilityNote: 'Junior CV — not Junior Deep Learning Engineer (non-vision) or BI Developer.' }),
    r('Vision AI Trainee', 'entry_trainee', 'Trainee on vision product teams supporting annotation tooling, model zoo evaluation and demo apps.', { priority: 40, eligibilityNote: 'Vision AI trainee — not generic AI Solutions Trainee (LLM-focused).' }),
    r('Junior Computer Vision Engineer', 'junior', 'Develops image/video models, preprocessing and REST/gRPC inference services for vision features.', { priority: 50, eligibilityNote: 'Junior CV eng — not ML Engineer (tabular/NLP) or Data Scientist.' }),
    r('Image Processing Engineer (Junior)', 'junior', 'Focuses on classical CV — filters, geometry, stitching and hybrid ML/classical pipelines.', { priority: 60, eligibilityNote: 'Image processing — not Computer Vision Research Scientist or graphics engineer.' }),
    r('Video Analytics Engineer (Junior)', 'junior', 'Builds real-time video analytics — tracking, action recognition and stream ingestion.', { priority: 70, eligibilityNote: 'Video analytics — not Streaming Data Engineer (ETL/events) unless vision streams.' }),
    r('Edge Vision Engineer (Junior)', 'junior', 'Optimises models for embedded GPUs/TPUs, quantisation and on-device latency constraints.', { priority: 80, eligibilityNote: 'Edge vision — not Robotics Software Engineer (motion planning) unless advert combines.' }),
    r('Computer Vision Engineer', 'practitioner', 'Owns vision model lifecycle — data, training, evaluation metrics and production deployment.', { priority: 90, eligibilityNote: 'Core CV engineer — not AI Engineer (LLM) or generic ML Engineer.' }),
    r('Deep Learning Vision Engineer', 'practitioner', 'Specialises in CNN/ViT architectures, detection/segmentation and GPU training optimisation.', { priority: 100, eligibilityNote: 'DL vision — not Deep Learning Engineer (non-vision) unless scope overlaps.' }),
    r('3D Vision Engineer', 'practitioner', 'Works on depth estimation, point clouds, SLAM or NeRF-style 3D reconstruction pipelines.', { priority: 110, eligibilityNote: '3D vision — not Robotics Software Engineer (full stack) unless robotics advert.' }),
    r('Medical Imaging Engineer', 'practitioner', 'Develops regulated-adjacent imaging AI with annotation QA, DICOM workflows and validation docs.', { priority: 120, eligibilityNote: 'Medical imaging CV — not clinical radiologist; software/engineering remit.' }),
    r('Senior Computer Vision Engineer', 'senior', 'Leads multi-camera vision programmes, dataset governance and mentors junior CV engineers.', { priority: 130, eligibilityNote: 'Senior CV — not Senior ML Engineer or Senior AI Engineer.' }),
    r('Senior Deep Learning Vision Engineer', 'senior', 'Authority on SOTA vision models, labelling strategy and production accuracy/latency trade-offs.', { priority: 140, eligibilityNote: 'Senior DL vision — not Computer Vision Research Scientist (publications).' }),
    r('Senior Video Analytics Engineer', 'senior', 'Owns large-scale video pipelines, edge/cloud split and incident detection quality bars.', { priority: 150, eligibilityNote: 'Senior video — not Senior Streaming Data Engineer (non-vision).' }),
    r('Principal Computer Vision Engineer', 'senior', 'Org-wide vision standards, tooling choices and cross-product technical leadership.', { priority: 160, eligibilityNote: 'Principal CV — distinct from Principal ML Engineer and Robotics architect.' }),
    r('Lead Computer Vision Engineer', 'lead_principal', 'Technical lead for CV squad — roadmap, design reviews and stakeholder metric alignment.', { priority: 170, eligibilityNote: 'CV technical lead — not ML Engineering Team Lead unless vision-only team.' }),
    r('Computer Vision Team Lead', 'lead_principal', 'Leads CV delivery workstreams, reusable training templates and evaluation harnesses.', { priority: 180, eligibilityNote: 'CV delivery lead — not AI Engineering Team Lead.' }),
    r('Lead Edge Vision Engineer', 'lead_principal', 'Sets edge deployment patterns, hardware targets and on-device monitoring for vision models.', { priority: 190, eligibilityNote: 'Lead edge vision — not Lead Robotics Software Engineer unless combined.' }),
    r('Computer Vision Architect', 'architect_specialist', 'Designs vision platform architecture — data loops, labelling, training and serving for products.', { priority: 200, eligibilityNote: 'CV architecture — not AI Solution Architect (LLM) or Data Architect.' }),
    r('Vision AI Architect', 'architect_specialist', 'Enterprise vision AI reference designs, camera/sensor integration and MLOps for vision.', { priority: 210, eligibilityNote: 'Vision AI architecture — not Enterprise BI Architect or ML Platform Architect alone.' }),
    r('Perception Systems Architect', 'architect_specialist', 'Architects multi-sensor perception stacks bridging CV, calibration and downstream robotics.', { priority: 220, eligibilityNote: 'Perception architecture — overlaps robotics; title distinct from Robotics Software Architect.' }),
    r('Computer Vision Engineering Manager', 'manager_head', 'Line manager for CV engineers — hiring, delivery and vision product partnership.', { priority: 230, eligibilityNote: 'CV people manager — not ML Engineering Manager or AI Manager.' }),
    r('Head of Computer Vision', 'manager_head', 'Owns CV engineering function, dataset strategy and senior vision hiring.', { priority: 240, eligibilityNote: 'Head of CV — not Head of AI or Head of Robotics unless combined remit.' }),
    r('Head of Vision AI', 'manager_head', 'Leads vision AI product engineering across retail, security, manufacturing or health verticals.', { priority: 250, eligibilityNote: 'Vision AI leadership — not Head of BI or Head of Analytics.' }),
    r('Director of Computer Vision', 'director_executive', 'Executive owner of computer vision capability, investment and vision product portfolio.', { priority: 260, eligibilityNote: 'Director CV — distinct from Director of AI Engineering or Director of ML.' }),
    r('VP Computer Vision', 'director_executive', 'VP-level accountability for vision platforms, partnerships and enterprise vision rollout.', { priority: 270, eligibilityNote: 'VP CV — not VP Machine Learning or Chief AI Officer.' }),
    r('Computer Vision Research Scientist', 'academic_research', 'Conducts vision research — detection theory, 3D vision or efficient architectures — with publications.', { priority: 280, isResearchRole: true, isAcademicRole: false, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'CV research — not production Computer Vision Engineer or ML Engineer.' }),
    r('Research Fellow (Computer Vision)', 'academic_research', 'Postdoctoral fellow in vision/graphics/robotics perception labs with grant research outputs.', { priority: 290, isResearchRole: true, isAcademicRole: false, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'CV fellowship — not Senior Computer Vision Engineer in industry R&D without papers.' }),
    r('Lecturer in Computer Vision', 'academic_research', 'University teaching and research in computer vision with PhD and publication expectations.', { priority: 300, isResearchRole: false, isAcademicRole: true, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'Academic CV lectureship — not corporate vision trainer or annotation team lead.' }),
  ],
}

// ---------------------------------------------------------------------------
// 8) Robotics Software — IET (~27 industry + 3 academic_research = 30)
// ---------------------------------------------------------------------------
const ROBOTICS_SOFTWARE: SpecialismPack = {
  slug: 'robotics-software',
  label: 'Robotics Software',
  professionalBody: 'Institution of Engineering and Technology (IET)',
  relatedBodies: ['British Computer Society (BCS)', 'Institution of Mechanical Engineers (IMechE)'],
  sources: ['prospects_robotics_engineer', 'iet_robotics_automation', 'ros_community_uk', 'uk_robotics_network'],
  siblingSlugs: siblings('robotics-software'),
  roles: [
    r('Graduate Robotics Software Engineer', 'entry_trainee', 'Entry role supporting ROS nodes, simulation tests and robot API integrations on graduate schemes.', { priority: 10, eligibilityNote: 'Robotics software entry — distinct from Graduate CV Engineer and embedded hardware engineer.' }),
    r('Robotics Software Apprentice', 'entry_trainee', 'Apprenticeship assisting robot bring-up, logging, CI for firmware/software stacks under robotics engineers.', { priority: 20, eligibilityNote: 'Robotics software apprentice — not mechanical fitter or pure electrical apprentice.' }),
    r('Junior Robotics Developer (Graduate)', 'entry_trainee', 'Develops motion/control interfaces, sensor drivers and integration tests in sim and lab.', { priority: 30, eligibilityNote: 'Junior robotics dev — not Junior AI Engineer or ML Engineer unless robot ML advert.' }),
    r('Robot Software Trainee', 'entry_trainee', 'Structured trainee supporting deployment scripts, calibration tools and field issue reproduction.', { priority: 40, eligibilityNote: 'Robot software trainee — not generic software graduate without robotics remit.' }),
    r('Junior Robotics Software Engineer', 'junior', 'Implements autonomy modules, state machines and hardware abstraction layers for robots.', { priority: 50, eligibilityNote: 'Junior robotics SW — not Computer Vision Engineer unless perception-only team.' }),
    r('ROS Developer (Junior)', 'junior', 'Builds ROS/ROS2 packages, launch files, message schemas and bag analysis workflows.', { priority: 60, eligibilityNote: 'ROS developer — not Streaming Data Engineer or backend API engineer.' }),
    r('Robot Simulation Engineer (Junior)', 'junior', 'Develops Gazebo/Isaac/Mujoco simulations, scenario tests and digital-twin hooks.', { priority: 70, eligibilityNote: 'Simulation engineer — not game developer unless robotics simulation explicit.' }),
    r('Fleet Robotics Engineer (Junior)', 'junior', 'Supports multi-robot orchestration, OTA updates and telemetry for deployed robot fleets.', { priority: 80, eligibilityNote: 'Fleet robotics — not DevOps/SRE unless robot fleet platform scoped.' }),
    r('Robotics Software Engineer', 'practitioner', 'Owns autonomy stack components — localisation, planning interfaces, safety monitors and APIs.', { priority: 90, eligibilityNote: 'Core robotics SW — not AI Engineer (LLM) or Data Engineer.' }),
    r('Autonomy Software Engineer', 'practitioner', 'Develops navigation, behaviour trees and mission planning software for mobile or manipulator robots.', { priority: 100, eligibilityNote: 'Autonomy SW — not Autonomous Vehicle ML Engineer unless same robotics domain advert.' }),
    r('Robot Perception Software Engineer', 'practitioner', 'Integrates lidar/camera/radar drivers and fusion nodes into robotics middleware stacks.', { priority: 110, eligibilityNote: 'Perception SW in robotics — not standalone Computer Vision Engineer product team.' }),
    r('Manipulation Software Engineer', 'practitioner', 'Implements grasp planning, arm control SDK integrations and teach-pendant workflows.', { priority: 120, eligibilityNote: 'Manipulation SW — not mechanical design engineer or PLC programmer.' }),
    r('Senior Robotics Software Engineer', 'senior', 'Leads robot software releases, safety cases (software) and mentors junior robotics engineers.', { priority: 130, eligibilityNote: 'Senior robotics SW — not Senior ML Engineer or Senior AI Engineer.' }),
    r('Senior Autonomy Engineer', 'senior', 'Authority on navigation stack tuning, field reliability and sim-to-real validation programmes.', { priority: 140, eligibilityNote: 'Senior autonomy — not Senior Computer Vision Engineer unless perception-led advert.' }),
    r('Senior ROS Engineer', 'senior', 'Owns robotics middleware standards, build systems and cross-team ROS package governance.', { priority: 150, eligibilityNote: 'Senior ROS — not Senior Data Platform Engineer or MLOps Engineer.' }),
    r('Principal Robotics Software Engineer', 'senior', 'Org-wide robotics software patterns, safety software practices and technical leadership.', { priority: 160, eligibilityNote: 'Principal robotics — distinct from Principal ML Engineer and CV architect.' }),
    r('Lead Robotics Software Engineer', 'lead_principal', 'Technical lead for robotics squad — architecture decisions, field issue triage and roadmap.', { priority: 170, eligibilityNote: 'Robotics technical lead — not ML Engineering Team Lead.' }),
    r('Robotics Software Team Lead', 'lead_principal', 'Leads robotics delivery workstreams, release trains and reusable robot software modules.', { priority: 180, eligibilityNote: 'Robotics delivery lead — not Computer Vision Team Lead unless same team.' }),
    r('Lead Autonomy Software Engineer', 'lead_principal', 'Sets autonomy software standards, simulation gates and cross-robot platform adoption.', { priority: 190, eligibilityNote: 'Lead autonomy — not Lead AI Engineer or Lead Data Engineer.' }),
    r('Robotics Software Architect', 'architect_specialist', 'Designs robot software reference architectures, middleware choices and safety software boundaries.', { priority: 200, eligibilityNote: 'Robotics SW architecture — not AI Solution Architect or Data Architect.' }),
    r('Autonomous Systems Architect', 'architect_specialist', 'Enterprise architecture for autonomous robots — fleet ops, OTA, telemetry and integration APIs.', { priority: 210, eligibilityNote: 'Autonomous systems — not Enterprise BI Architect or ML Platform Architect.' }),
    r('Robot Platform Architect', 'architect_specialist', 'Defines shared robot platform SDKs, hardware abstraction and multi-product software reuse.', { priority: 220, eligibilityNote: 'Robot platform — not Data Platform Architect (analytics warehouse).' }),
    r('Robotics Engineering Manager', 'manager_head', 'Line manager for robotics software engineers — hiring, field support escalation and delivery.', { priority: 230, eligibilityNote: 'Robotics people manager — not ML Engineering Manager or AI Manager.' }),
    r('Head of Robotics Software', 'manager_head', 'Owns robotics software function, platform roadmap and senior robotics hiring.', { priority: 240, eligibilityNote: 'Head of robotics SW — not Head of Computer Vision unless combined perception team.' }),
    r('Head of Autonomous Systems', 'manager_head', 'Leads autonomous robot programmes spanning software, field ops partnership and safety governance.', { priority: 250, eligibilityNote: 'Autonomous systems head — not Head of BI or Head of Data Analytics.' }),
    r('Director of Robotics Software', 'director_executive', 'Executive owner of robotics software capability, investment and product autonomy strategy.', { priority: 260, eligibilityNote: 'Director robotics SW — distinct from Director of AI or Director of ML.' }),
    r('VP Robotics Engineering', 'director_executive', 'VP-level leadership of robotics software/engineering portfolio and strategic partnerships.', { priority: 270, eligibilityNote: 'VP robotics — not VP Machine Learning or Chief AI Officer.' }),
    r('Robotics Research Scientist', 'academic_research', 'Conducts robotics research — planning, learning or human-robot interaction — with publications.', { priority: 280, isResearchRole: true, isAcademicRole: false, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'Robotics research — not production Robotics Software Engineer or field deployment lead.' }),
    r('Research Fellow (Robotics)', 'academic_research', 'Postdoctoral fellow in robotics labs advancing algorithms or fieldable robot systems research.', { priority: 290, isResearchRole: true, isAcademicRole: false, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'Robotics fellowship — not Senior Autonomy Engineer in industry without research output.' }),
    r('Lecturer in Robotics (Software Systems)', 'academic_research', 'University teaching and research in robotics software with PhD and peer-reviewed expectations.', { priority: 300, isResearchRole: false, isAcademicRole: true, academicRequirement: 'phd_relevant', fitClassification: 'academic_or_research', eligibilityNote: 'Academic robotics lectureship — not robotics trainer or technician instructor.' }),
  ],
}

export const DATA_PACKS: SpecialismPack[] = [
  DATA_ENGINEERING,
  DATA_ANALYTICS,
  DATA_SCIENCE,
  ARTIFICIAL_INTELLIGENCE,
  MACHINE_LEARNING,
  BUSINESS_INTELLIGENCE,
  COMPUTER_VISION,
  ROBOTICS_SOFTWARE,
]
