import { r, type SpecialismPack } from './shared'

const QA_SOFTWARE_TESTING: SpecialismPack = {
  slug: 'qa-software-testing',
  label: 'QA & Software Testing',
  professionalBody: 'BCS, The Chartered Institute for IT',
  relatedBodies: ['ISTQB', 'Ministry of Testing', 'TechSkills'],
  sources: ['prospects_software_tester', 'national_careers_service_software_tester', 'bcs_careers', 'istqb_foundation'],
  siblingSlugs: [
    'game-development',
    'embedded-systems',
    'iot',
    'erp-crm-systems',
    'enterprise-architecture',
    'solutions-architecture',
    'blockchain',
    'other-it-technology'
  ],
  roles: [
    r('QA Apprentice (Software Testing)', 'entry_trainee', 'Entry apprenticeship route into manual and exploratory software testing in UK product and consultancy teams.', { priority: 10, eligibilityNote: 'Immediate QA & testing apprenticeship pathway — not general IT Support or Software Development delivery roles.' }),
    r('Graduate QA Tester', 'entry_trainee', 'Graduate entry executing test cases, logging defects and supporting regression cycles under test lead supervision.', { priority: 20, eligibilityNote: 'Graduate software testing entry — not Software Developer or IT Support first-line roles.' }),
    r('Software Test Analyst (Entry)', 'entry_trainee', 'Runs structured test scripts, documents results and supports UAT preparation for UK software releases.', { priority: 30, eligibilityNote: 'Entry test analysis within QA — not Business Analyst or Data Analyst roles.' }),
    r('Trainee Test Engineer (Software Quality)', 'entry_trainee', 'Builds foundational test execution and basic automation skills on supervised QA workstreams.', { priority: 40, eligibilityNote: 'Trainee quality engineering — not DevOps or Platform Engineering entry routes.' }),
    r('Junior QA Engineer', 'junior', 'Executes functional and regression testing with growing ownership of test areas on agile squads.', { priority: 50, eligibilityNote: 'Junior QA engineering — not Junior Software Developer or Junior DevOps Engineer.' }),
    r('Junior Test Analyst', 'junior', 'Analyses requirements for testability, designs test conditions and reports defects with traceability.', { priority: 60, eligibilityNote: 'Junior test analysis — not Junior Business Analyst or Junior Data Analyst.' }),
    r('Manual Software Tester (Junior)', 'junior', 'Performs exploratory and scripted manual testing for web and mobile products in UK delivery teams.', { priority: 70, eligibilityNote: 'Manual testing specialism — not Frontend or Backend Developer junior roles.' }),
    r('Junior Automation Tester', 'junior', 'Develops basic UI and API automated checks using frameworks such as Selenium or Cypress under senior guidance.', { priority: 80, eligibilityNote: 'Junior test automation — not Junior Software Developer or SDET in a pure development squad.' }),
    r('QA Engineer (Software Testing)', 'practitioner', 'Owns test planning and execution for product features including functional, regression and smoke coverage.', { priority: 90, eligibilityNote: 'Mid-level QA engineer — not Mid-Level Software Developer or DevOps Engineer.' }),
    r('Test Analyst (Mid-Level)', 'practitioner', 'Designs test scenarios, manages defect triage and supports release readiness for UK software programmes.', { priority: 100, eligibilityNote: 'Mid-level test analysis — not Business Intelligence or Data Analytics analysis roles.' }),
    r('Automation Test Engineer (QA)', 'practitioner', 'Builds and maintains automated test suites for APIs and UI with CI integration in UK agile teams.', { priority: 110, eligibilityNote: 'QA automation engineering — not Backend Developer or Platform Engineer automation focus.' }),
    r('SDET (Software Testing)', 'practitioner', 'Combines testing discipline with engineering skills to build test frameworks and quality gates for delivery pipelines.', { priority: 120, eligibilityNote: 'Software testing SDET — not general Software Development Engineer in Test outside QA context.' }),
    r('Performance Test Engineer (QA)', 'practitioner', 'Plans and executes load, stress and soak testing using tools such as JMeter or k6 for UK applications.', { priority: 130, eligibilityNote: 'Performance testing within QA — not Site Reliability Engineer or DevOps performance tuning roles.' }),
    r('Accessibility Test Engineer (QA)', 'practitioner', 'Validates WCAG compliance and inclusive design through specialist accessibility testing practices.', { priority: 140, eligibilityNote: 'Accessibility testing specialism — not UX Designer or Frontend Developer roles.' }),
    r('Senior QA Engineer', 'senior', 'Leads quality strategy for complex domains, mentors testers and drives shift-left practices on programmes.', { priority: 150, eligibilityNote: 'Senior QA — not Senior Software Developer or Senior DevOps Engineer.' }),
    r('Senior Test Analyst', 'senior', 'Owns test approach for major releases, risk-based testing and stakeholder reporting in UK enterprises.', { priority: 160, eligibilityNote: 'Senior test analysis — not Senior Business Analyst or Enterprise Architect roles.' }),
    r('Senior Automation Engineer (Testing)', 'senior', 'Architects automation frameworks, coding standards and reusable libraries for large UK test estates.', { priority: 170, eligibilityNote: 'Senior test automation — not Senior Backend Developer or Cloud Engineer.' }),
    r('Senior SDET (Software Quality)', 'senior', 'Sets engineering standards for test automation, pipeline quality gates and observability of test outcomes.', { priority: 180, eligibilityNote: 'Senior SDET in QA — not Senior Platform or Infrastructure Engineer.' }),
    r('Senior Performance Test Engineer', 'senior', 'Leads non-functional test strategy, capacity modelling and performance sign-off for critical UK systems.', { priority: 190, eligibilityNote: 'Senior performance testing — not Senior SRE or Capacity Planning in operations teams.' }),
    r('QA Lead (Software Testing)', 'lead_principal', 'Leads QA workstreams, coordinates testers across squads and owns quality metrics for releases.', { priority: 210, eligibilityNote: 'QA lead — not Engineering Team Lead or Scrum Master roles.' }),
    r('Test Lead (Software Delivery)', 'lead_principal', 'Directs test execution, resource planning and defect management for multi-squad UK programmes.', { priority: 220, eligibilityNote: 'Test lead — not Project Manager or Delivery Manager without testing accountability.' }),
    r('Quality Engineering Lead', 'lead_principal', 'Drives quality engineering culture, tooling adoption and continuous improvement across testing practice.', { priority: 230, eligibilityNote: 'Quality engineering lead — not DevOps Lead or Platform Engineering Lead.' }),
    r('Test Architect (Software Quality)', 'architect_specialist', 'Designs enterprise test architecture, tooling strategy and quality frameworks for large UK organisations.', { priority: 240, eligibilityNote: 'Test architecture — not Solutions Architect or Enterprise Architect roles.' }),
    r('Quality Assurance Architect', 'architect_specialist', 'Defines quality models, test data strategy and non-functional quality standards across portfolios.', { priority: 250, eligibilityNote: 'QA architecture — not Cloud Architect or Security Architect roles.' }),
    r('Automation Test Architect (QA)', 'architect_specialist', 'Owns automation architecture, framework selection and CI/CD quality integration at scale.', { priority: 260, eligibilityNote: 'Automation test architecture — not DevOps Architect or Platform Architect.' }),
    r('QA Manager (Software Testing)', 'manager_head', 'Manages QA teams, hiring, performance and quality KPIs for UK software delivery organisations.', { priority: 270, eligibilityNote: 'QA management — not Engineering Manager for product development squads only.' }),
    r('Head of Software Testing', 'manager_head', 'Leads testing function, vendor strategy and quality governance across business units.', { priority: 280, eligibilityNote: 'Head of testing — not Head of Engineering or Head of DevOps.' }),
    r('Test Manager (Software Programmes)', 'manager_head', 'Owns test planning, resourcing and release quality for major UK transformation programmes.', { priority: 290, eligibilityNote: 'Test programme management — not generic IT Programme Manager without QA scope.' }),
    r('Director of Quality Engineering', 'director_executive', 'Executive ownership of quality engineering strategy, investment and organisational testing capability.', { priority: 300, eligibilityNote: 'Director of quality engineering — not CTO or VP Engineering without QA remit.' }),
    r('Director of Software Testing', 'director_executive', 'Senior leadership of enterprise testing centres of excellence and quality transformation.', { priority: 310, eligibilityNote: 'Director of software testing — not Director of Software Development or IT Operations.' }),
  ],
}

const GAME_DEVELOPMENT: SpecialismPack = {
  slug: 'game-development',
  label: 'Game Development',
  professionalBody: 'TIGA',
  relatedBodies: ['BCS', 'UKIE', 'ScreenSkills'],
  sources: ['prospects_game_developer', 'national_careers_service_game_developer', 'tiga_careers', 'ukie_skills'],
  siblingSlugs: [
    'qa-software-testing',
    'embedded-systems',
    'iot',
    'erp-crm-systems',
    'enterprise-architecture',
    'solutions-architecture',
    'blockchain',
    'other-it-technology'
  ],
  roles: [
    r('Game Development Apprentice', 'entry_trainee', 'Entry apprenticeship learning engine basics, C++ or C# and studio pipelines in UK game companies.', { priority: 10, eligibilityNote: 'Game development apprenticeship — not general Software Development or Web Development apprenticeships.' }),
    r('Graduate Game Developer', 'entry_trainee', 'Graduate entry implementing gameplay features, bug fixes and prototype systems in UK studios.', { priority: 20, eligibilityNote: 'Graduate game developer — not Graduate Software Developer in non-games industries.' }),
    r('Junior Game Programmer (Entry)', 'entry_trainee', 'Supports gameplay scripting, debugging and content integration under senior game programmers.', { priority: 30, eligibilityNote: 'Entry game programming — not Embedded Systems or Robotics Software roles.' }),
    r('Trainee Level Designer (Games)', 'entry_trainee', 'Assists blockout, pacing and player flow tasks using Unreal or Unity under design supervision.', { priority: 40, eligibilityNote: 'Trainee level design — not general UX Designer or Web Designer roles.' }),
    r('Junior Gameplay Programmer', 'junior', 'Implements player mechanics, AI behaviours and interaction systems for UK game projects.', { priority: 50, eligibilityNote: 'Junior gameplay programming — not Junior Backend Developer or Frontend Developer.' }),
    r('Junior Engine Programmer (Games)', 'junior', 'Works on rendering, physics or engine subsystems with guidance from senior engine engineers.', { priority: 60, eligibilityNote: 'Junior engine programming — not general Systems Programming outside games.' }),
    r('Junior Tools Programmer (Games)', 'junior', 'Builds editor extensions, pipeline tools and content automation for UK game production teams.', { priority: 70, eligibilityNote: 'Junior tools programming for games — not DevOps or Internal Tools Engineer in SaaS.' }),
    r('Junior Technical Artist (Games)', 'junior', 'Bridges art and engineering through shaders, rigging scripts and asset pipeline support.', { priority: 80, eligibilityNote: 'Junior technical artist — not VFX Artist in film or general 3D Artist roles.' }),
    r('Gameplay Programmer (Games)', 'practitioner', 'Owns gameplay systems, combat loops, progression and multiplayer interactions in shipped titles.', { priority: 90, eligibilityNote: 'Mid-level gameplay programming — not general Software Engineer in fintech or enterprise IT.' }),
    r('Game Engine Programmer', 'practitioner', 'Develops core engine features, optimisation and platform abstraction for UK studio technology stacks.', { priority: 100, eligibilityNote: 'Game engine programming — not Embedded Firmware Engineer or Cloud Platform Engineer.' }),
    r('Technical Artist (Games Studio)', 'practitioner', 'Creates shader graphs, procedural content tools and performance-aware art pipelines for games.', { priority: 110, eligibilityNote: 'Technical artist in games — not AR/VR generalist or Computer Vision Engineer.' }),
    r('Tools Developer (Game Studio)', 'practitioner', 'Builds production tools, build automation and content validation for game development pipelines.', { priority: 120, eligibilityNote: 'Game studio tools — not DevOps Engineer or Backend Developer tooling roles.' }),
    r('Multiplayer Game Programmer', 'practitioner', 'Implements networking, matchmaking integration and synchronisation for online UK game titles.', { priority: 130, eligibilityNote: 'Multiplayer game programming — not general Network Engineer or Backend API Developer.' }),
    r('UI Programmer (Games)', 'practitioner', 'Develops in-game menus, HUD systems and meta-game interfaces using engine UI frameworks.', { priority: 140, eligibilityNote: 'Game UI programming — not Frontend Web Developer or Mobile App Developer.' }),
    r('Senior Gameplay Programmer', 'senior', 'Leads complex gameplay features, mentoring and technical design for flagship UK game products.', { priority: 150, eligibilityNote: 'Senior gameplay — not Senior Software Developer in non-games sectors.' }),
    r('Senior Engine Programmer (Games)', 'senior', 'Owns engine performance, memory and cross-platform delivery for AAA or live-service titles.', { priority: 160, eligibilityNote: 'Senior engine programming — not Senior Embedded Systems Engineer.' }),
    r('Senior Technical Artist (Games)', 'senior', 'Sets technical art standards, shader architecture and optimisation across art and engineering.', { priority: 170, eligibilityNote: 'Senior technical artist — not Senior Computer Vision or Graphics Research roles.' }),
    r('Senior Tools Programmer (Games)', 'senior', 'Architects tooling strategy, DCC integrations and artist/engineer workflow for large studios.', { priority: 180, eligibilityNote: 'Senior game tools — not Senior DevOps or Platform Engineer.' }),
    r('Senior Game Designer (Technical)', 'senior', 'Combines systems design with technical prototyping for mechanics, economy and live ops features.', { priority: 190, eligibilityNote: 'Technical game design — not Product Manager or Business Analyst roles.' }),
    r('Gameplay Programming Lead', 'lead_principal', 'Leads gameplay engineering team, code reviews and feature delivery for UK game projects.', { priority: 210, eligibilityNote: 'Gameplay lead — not Engineering Manager in enterprise software companies.' }),
    r('Engine Programming Lead (Games)', 'lead_principal', 'Directs engine team priorities, platform roadmap and technical debt for studio engine stack.', { priority: 220, eligibilityNote: 'Engine programming lead — not Cloud Infrastructure Lead or Systems Architect.' }),
    r('Lead Tools Programmer (Games)', 'lead_principal', 'Leads tools engineering squad building pipeline automation and content systems for production.', { priority: 230, eligibilityNote: 'Lead game tools — not Lead DevOps Engineer or Lead Backend Developer.' }),
    r('Game Systems Architect', 'architect_specialist', 'Designs gameplay framework architecture, modular systems and scalability for live game services.', { priority: 240, eligibilityNote: 'Game systems architecture — not Enterprise Architect or Solutions Architect.' }),
    r('Game Technical Architect', 'architect_specialist', 'Owns technical vision for game project including engine choices, networking and platform strategy.', { priority: 250, eligibilityNote: 'Game technical architecture — not Cloud Solutions Architect in enterprise IT.' }),
    r('Online Game Services Architect', 'architect_specialist', 'Architects backend services, matchmaking, telemetry and live ops infrastructure for games.', { priority: 260, eligibilityNote: 'Online game services — not general Cloud Architect or Backend Architect outside games.' }),
    r('Game Development Manager', 'manager_head', 'Manages game engineering teams, milestones and cross-discipline delivery in UK studios.', { priority: 270, eligibilityNote: 'Game development management — not generic IT Project Manager.' }),
    r('Studio Technical Manager (Games)', 'manager_head', 'Oversees technical production, engine adoption and engineering resourcing across game projects.', { priority: 280, eligibilityNote: 'Studio technical management — not IT Operations Manager.' }),
    r('Head of Game Engineering', 'manager_head', 'Leads engineering function across titles, hiring and technical standards for UK game studio.', { priority: 290, eligibilityNote: 'Head of game engineering — not Head of Software Development in non-games firms.' }),
    r('Director of Game Development', 'director_executive', 'Executive leadership of game product engineering, portfolio and studio technical strategy.', { priority: 300, eligibilityNote: 'Director of game development — not Director of Software Engineering in enterprise.' }),
    r('Studio Technical Director (Games)', 'director_executive', 'Top technical authority for studio technology, engine strategy and multi-project architecture.', { priority: 310, eligibilityNote: 'Studio technical director — not Enterprise Architect or CTO without games remit.' }),
  ],
}

const EMBEDDED_SYSTEMS: SpecialismPack = {
  slug: 'embedded-systems',
  label: 'Embedded Systems',
  professionalBody: 'IET',
  relatedBodies: ['BCS', 'Engineering Council', 'ARM'],
  sources: ['prospects_embedded_software_engineer', 'national_careers_service_software_developer', 'iet_careers', 'bcs_careers'],
  siblingSlugs: [
    'qa-software-testing',
    'game-development',
    'iot',
    'erp-crm-systems',
    'enterprise-architecture',
    'solutions-architecture',
    'blockchain',
    'other-it-technology'
  ],
  roles: [
    r('Embedded Systems Apprentice', 'entry_trainee', 'Apprenticeship developing firmware, microcontroller programming and hardware-software integration skills.', { priority: 10, eligibilityNote: 'Embedded apprenticeship — not IT Support, Networking or general Software Development apprenticeships.' }),
    r('Graduate Embedded Software Engineer', 'entry_trainee', 'Graduate entry writing C/C++ firmware, drivers and board bring-up under senior embedded engineers.', { priority: 20, eligibilityNote: 'Graduate embedded — not Graduate Software Developer for web/cloud products.' }),
    r('Junior Firmware Engineer', 'entry_trainee', 'Supports firmware development, debugging with JTAG and unit testing on target hardware platforms.', { priority: 30, eligibilityNote: 'Junior firmware — not Junior DevOps or Junior Backend Developer roles.' }),
    r('Trainee Embedded Test Engineer', 'entry_trainee', 'Executes hardware-in-the-loop tests, regression on devices and lab validation under supervision.', { priority: 40, eligibilityNote: 'Embedded test entry — not QA Software Testing for web applications only.' }),
    r('Junior Embedded Software Engineer', 'junior', 'Develops RTOS tasks, peripheral drivers and communication stacks on ARM or MCU platforms in UK industry.', { priority: 50, eligibilityNote: 'Junior embedded — not Junior IoT Cloud Developer or Robotics Software roles.' }),
    r('Junior FPGA Engineer (Embedded)', 'junior', 'Supports VHDL/Verilog development and verification for embedded digital logic under senior engineers.', { priority: 60, eligibilityNote: 'Junior FPGA embedded — not general Digital Design outside embedded products.' }),
    r('Junior Device Driver Developer', 'junior', 'Implements and maintains kernel or bare-metal drivers for sensors, buses and I/O subsystems.', { priority: 70, eligibilityNote: 'Device driver development — not Systems Administrator or Network Engineer roles.' }),
    r('Junior Hardware-Software Integration Engineer', 'junior', 'Integrates firmware with PCB designs, validates prototypes and supports manufacturing test.', { priority: 80, eligibilityNote: 'HW-SW integration — not Mechanical Engineering or pure Hardware Design roles.' }),
    r('Embedded Software Engineer', 'practitioner', 'Owns firmware modules, bootloaders and real-time constraints for UK automotive, medical or industrial devices.', { priority: 90, eligibilityNote: 'Mid-level embedded — not Mid-Level Backend Developer or Cloud Engineer.' }),
    r('Firmware Engineer (Embedded Products)', 'practitioner', 'Develops production firmware, OTA update mechanisms and security hardening for connected devices.', { priority: 100, eligibilityNote: 'Firmware engineering — not IoT Platform Engineer focused on cloud-only stacks.' }),
    r('RTOS Engineer (Embedded Systems)', 'practitioner', 'Designs task scheduling, memory management and deterministic behaviour on FreeRTOS, Zephyr or similar.', { priority: 110, eligibilityNote: 'RTOS specialism — not general Operating Systems admin or DevOps roles.' }),
    r('Embedded Linux Engineer', 'practitioner', 'Builds Yocto or Buildroot images, kernel tuning and userspace services for embedded Linux products.', { priority: 120, eligibilityNote: 'Embedded Linux — not Linux Systems Administrator in datacentre IT.' }),
    r('FPGA Design Engineer (Embedded)', 'practitioner', 'Develops programmable logic for signal processing, control and interfacing in embedded UK products.', { priority: 130, eligibilityNote: 'Embedded FPGA — not general ASIC design outside embedded context.' }),
    r('Embedded Security Engineer', 'practitioner', 'Implements secure boot, crypto modules and threat mitigation for firmware on constrained devices.', { priority: 140, eligibilityNote: 'Embedded security — not Cyber Security Analyst or SOC roles in IT security operations.' }),
    r('Senior Embedded Software Engineer', 'senior', 'Leads complex firmware architecture, code review and mentoring on safety-critical or high-volume devices.', { priority: 150, eligibilityNote: 'Senior embedded — not Senior Software Developer in SaaS or web stacks.' }),
    r('Senior Firmware Engineer', 'senior', 'Owns firmware lifecycle, release qualification and cross-team technical decisions for device platforms.', { priority: 160, eligibilityNote: 'Senior firmware — not Senior DevOps or Platform Engineer.' }),
    r('Senior Embedded Linux Engineer', 'senior', 'Sets BSP standards, kernel maintenance and long-term support strategy for embedded Linux fleets.', { priority: 170, eligibilityNote: 'Senior embedded Linux — not Senior Cloud or Infrastructure Engineer.' }),
    r('Senior FPGA Engineer (Embedded Systems)', 'senior', 'Leads FPGA architecture, timing closure and verification for performance-critical embedded systems.', { priority: 180, eligibilityNote: 'Senior embedded FPGA — not general VLSI roles outside product firmware context.' }),
    r('Senior Hardware-Software Integration Engineer', 'senior', 'Owns end-to-end integration, EMC considerations and production readiness for embedded products.', { priority: 190, eligibilityNote: 'Senior HW-SW integration — not Senior Mechanical or Electrical Engineer roles.' }),
    r('Embedded Engineering Lead', 'lead_principal', 'Leads embedded squad delivery, technical standards and cross-functional coordination with hardware teams.', { priority: 210, eligibilityNote: 'Embedded lead — not Engineering Lead in web or mobile product teams.' }),
    r('Firmware Team Lead', 'lead_principal', 'Directs firmware developers, sprint planning and quality gates for device software releases.', { priority: 220, eligibilityNote: 'Firmware team lead — not Backend Team Lead or DevOps Lead.' }),
    r('Embedded Systems Lead Engineer', 'lead_principal', 'Technical lead across multiple embedded workstreams including architecture decisions and risk management.', { priority: 230, eligibilityNote: 'Embedded systems lead — not Solutions Architecture Lead in enterprise IT.' }),
    r('Embedded Systems Architect', 'architect_specialist', 'Designs firmware architecture, hardware abstraction layers and platform strategy for device portfolios.', { priority: 240, eligibilityNote: 'Embedded systems architecture — not Enterprise Architect or Cloud Architect.' }),
    r('Firmware Architect (Embedded Products)', 'architect_specialist', 'Defines firmware platform, modularisation and upgrade strategy for long-life embedded products.', { priority: 250, eligibilityNote: 'Firmware architecture — not Software Architect for enterprise applications.' }),
    r('Embedded Platform Architect', 'architect_specialist', 'Owns reference designs, chip selection and cross-product embedded platform standards.', { priority: 260, eligibilityNote: 'Embedded platform architecture — not IoT Cloud Platform Architect.' }),
    r('Embedded Engineering Manager', 'manager_head', 'Manages embedded software teams, hiring and delivery for UK device product companies.', { priority: 270, eligibilityNote: 'Embedded engineering management — not IT Operations or Software Development Manager for apps.' }),
    r('Head of Embedded Software', 'manager_head', 'Leads embedded function, toolchain investment and engineering excellence across device lines.', { priority: 280, eligibilityNote: 'Head of embedded — not Head of Engineering for cloud-native product orgs.' }),
    r('Firmware Development Manager', 'manager_head', 'Owns firmware roadmap, vendor coordination and release governance for hardware product businesses.', { priority: 290, eligibilityNote: 'Firmware management — not DevOps Manager or Infrastructure Manager.' }),
    r('Director of Embedded Systems', 'director_executive', 'Executive leadership of embedded engineering capability, R&D and product technology strategy.', { priority: 300, eligibilityNote: 'Director of embedded — not Director of IT or Cloud without device software remit.' }),
    r('Director of Device Software Engineering', 'director_executive', 'Senior portfolio leadership for firmware, embedded Linux and connected device software across UK org.', { priority: 310, eligibilityNote: 'Director of device software — not Director of Software Development for enterprise apps.' }),
  ],
}

const IOT: SpecialismPack = {
  slug: 'iot',
  label: 'IoT',
  professionalBody: 'BCS, The Chartered Institute for IT',
  relatedBodies: ['IET', 'AWS IoT', 'Microsoft Azure IoT'],
  sources: ['prospects_iot_developer', 'national_careers_service_software_developer', 'bcs_careers', 'tech_nation_skills'],
  siblingSlugs: [
    'qa-software-testing',
    'game-development',
    'embedded-systems',
    'erp-crm-systems',
    'enterprise-architecture',
    'solutions-architecture',
    'blockchain',
    'other-it-technology'
  ],
  roles: [
    r('IoT Apprentice (Connected Devices)', 'entry_trainee', 'Apprenticeship learning sensor integration, edge programming and device provisioning fundamentals.', { priority: 10, eligibilityNote: 'IoT apprenticeship — not IT Support or Networking apprenticeship routes.' }),
    r('Graduate IoT Developer', 'entry_trainee', 'Graduate entry building device firmware, edge agents and cloud connectivity for UK IoT solutions.', { priority: 20, eligibilityNote: 'Graduate IoT — not Graduate Embedded Engineer focused purely on non-connected firmware.' }),
    r('Junior IoT Software Engineer', 'entry_trainee', 'Supports MQTT integrations, device twins and telemetry pipelines under IoT platform engineers.', { priority: 30, eligibilityNote: 'Junior IoT software — not Junior Backend Developer without device/edge context.' }),
    r('Trainee IoT Solutions Analyst', 'entry_trainee', 'Assists requirements gathering, device catalogues and pilot deployments for connected product programmes.', { priority: 40, eligibilityNote: 'Trainee IoT analyst — not Business Analyst in ERP or CRM systems.' }),
    r('Junior Edge Computing Engineer (IoT)', 'junior', 'Develops edge applications, local processing and store-and-forward logic on gateways and devices.', { priority: 50, eligibilityNote: 'Junior edge IoT — not Junior Cloud Engineer without edge/device scope.' }),
    r('Junior IoT Platform Engineer', 'junior', 'Configures IoT hubs, device provisioning and rules engines on Azure IoT or AWS IoT Core.', { priority: 60, eligibilityNote: 'Junior IoT platform — not Junior DevOps Engineer for general CI/CD only.' }),
    r('Junior Device Integration Engineer (IoT)', 'junior', 'Integrates sensors, PLCs and third-party devices into IoT ingestion pipelines for UK industrial clients.', { priority: 70, eligibilityNote: 'Device integration IoT — not SCADA Engineer outside connected cloud context.' }),
    r('Junior IoT Data Engineer', 'junior', 'Builds telemetry streams, time-series storage and basic analytics for connected device fleets.', { priority: 80, eligibilityNote: 'Junior IoT data — not general Data Engineering for enterprise warehouses only.' }),
    r('IoT Software Engineer', 'practitioner', 'Owns end-to-end device-to-cloud features including protocols, security and fleet management.', { priority: 90, eligibilityNote: 'Mid-level IoT software — not Mid-Level Embedded Engineer without cloud connectivity.' }),
    r('Edge IoT Engineer', 'practitioner', 'Designs edge analytics, offline operation and local decision-making for UK smart building or industrial IoT.', { priority: 100, eligibilityNote: 'Edge IoT — not Edge CDN or general Cloud Edge roles without devices.' }),
    r('IoT Platform Engineer', 'practitioner', 'Operates IoT platforms, device lifecycle, OTA updates and multi-tenant device estates.', { priority: 110, eligibilityNote: 'IoT platform engineering — not Cloud Platform Engineer for general PaaS only.' }),
    r('IoT Solutions Developer', 'practitioner', 'Builds customer IoT solutions combining devices, APIs and dashboards for UK system integrators.', { priority: 120, eligibilityNote: 'IoT solutions development — not Solutions Architect without hands-on build.' }),
    r('Connected Product Engineer (IoT)', 'practitioner', 'Delivers connected features for consumer or industrial products including pairing, telemetry and alerts.', { priority: 130, eligibilityNote: 'Connected product IoT — not Mobile App Developer without device integration.' }),
    r('IoT Security Engineer', 'practitioner', 'Implements device identity, certificate rotation and IoT-specific threat models for UK deployments.', { priority: 140, eligibilityNote: 'IoT security — not Cyber Security Analyst focused on corporate IT only.' }),
    r('Senior IoT Software Engineer', 'senior', 'Leads architecture of device fleets, protocol choices and reliability for large-scale IoT programmes.', { priority: 150, eligibilityNote: 'Senior IoT — not Senior Backend Developer without connected device experience.' }),
    r('Senior Edge IoT Engineer', 'senior', 'Owns edge platform standards, containerised edge and hybrid cloud-edge patterns.', { priority: 160, eligibilityNote: 'Senior edge IoT — not Senior Cloud Architect without device/edge remit.' }),
    r('Senior IoT Platform Engineer', 'senior', 'Sets platform governance, scaling and cost optimisation for enterprise IoT estates in UK orgs.', { priority: 170, eligibilityNote: 'Senior IoT platform — not Senior DevOps Lead for general infrastructure.' }),
    r('Senior Connected Products Engineer', 'senior', 'Leads connected product roadmap, firmware-cloud coordination and field reliability.', { priority: 180, eligibilityNote: 'Senior connected products — not Senior Embedded Engineer without cloud product ownership.' }),
    r('Senior IoT Integration Engineer', 'senior', 'Owns complex integrations with ERP, CMMS and analytics platforms for industrial IoT.', { priority: 190, eligibilityNote: 'Senior IoT integration — not ERP Consultant or CRM Developer roles.' }),
    r('IoT Engineering Lead', 'lead_principal', 'Leads IoT delivery squads across edge, cloud and device workstreams for UK clients.', { priority: 210, eligibilityNote: 'IoT engineering lead — not Data Engineering Lead or Cloud Lead without IoT scope.' }),
    r('Edge Computing Lead (IoT)', 'lead_principal', 'Directs edge engineering teams, reference architectures and rollout standards.', { priority: 220, eligibilityNote: 'Edge lead IoT — not Network Engineering Lead.' }),
    r('Connected Devices Lead Engineer', 'lead_principal', 'Technical leadership across device software, connectivity and platform for IoT programmes.', { priority: 230, eligibilityNote: 'Connected devices lead — not Robotics Software Lead or Embedded Lead only.' }),
    r('IoT Solutions Architect', 'architect_specialist', 'Designs end-to-end IoT reference architectures spanning devices, edge, cloud and security.', { priority: 240, eligibilityNote: 'IoT solutions architecture — not bare Solutions Architect or Enterprise Architect.' }),
    r('IoT Platform Architect', 'architect_specialist', 'Defines IoT platform standards, multi-tenant models and integration patterns at scale.', { priority: 250, eligibilityNote: 'IoT platform architecture — not Cloud Architect without device connectivity focus.' }),
    r('Edge IoT Architect', 'architect_specialist', 'Architects edge topology, latency budgets and hybrid processing for UK smart infrastructure.', { priority: 260, eligibilityNote: 'Edge IoT architecture — not Network Architect or Data Architect roles.' }),
    r('IoT Engineering Manager', 'manager_head', 'Manages IoT engineering teams, partner ecosystems and delivery for connected solutions.', { priority: 270, eligibilityNote: 'IoT engineering management — not IT Operations Manager.' }),
    r('Head of IoT Engineering', 'manager_head', 'Leads IoT practice, pre-sales technical capability and centre of excellence.', { priority: 280, eligibilityNote: 'Head of IoT — not Head of Cloud or Head of Data without IoT remit.' }),
    r('Connected Products Manager (IoT)', 'manager_head', 'Owns connected product engineering delivery, roadmap and cross-functional device-cloud teams.', { priority: 290, eligibilityNote: 'Connected products manager — not Product Manager without engineering team leadership.' }),
    r('Director of IoT', 'director_executive', 'Executive ownership of IoT strategy, portfolio and organisational connected-device capability.', { priority: 300, eligibilityNote: 'Director of IoT — not Director of IT without connected product/device focus.' }),
    r('Director of Connected Devices', 'director_executive', 'Senior leadership of device connectivity, platform investment and IoT transformation programmes.', { priority: 310, eligibilityNote: 'Director of connected devices — not Director of Software Development for apps only.' }),
  ],
}

const ERP_CRM_SYSTEMS: SpecialismPack = {
  slug: 'erp-crm-systems',
  label: 'ERP / CRM Systems',
  professionalBody: 'BCS, The Chartered Institute for IT',
  relatedBodies: ['Microsoft', 'SAP', 'Salesforce'],
  sources: ['prospects_it_consultant', 'national_careers_service_it_consultant', 'bcs_careers', 'microsoft_dynamics_careers'],
  siblingSlugs: [
    'qa-software-testing',
    'game-development',
    'embedded-systems',
    'iot',
    'enterprise-architecture',
    'solutions-architecture',
    'blockchain',
    'other-it-technology'
  ],
  roles: [
    r('ERP CRM Apprentice (Business Systems)', 'entry_trainee', 'Apprenticeship supporting configuration, testing and user support on ERP or CRM platforms.', { priority: 10, eligibilityNote: 'ERP/CRM apprenticeship — not IT Support helpdesk or Software Development apprenticeship.' }),
    r('Graduate ERP Consultant', 'entry_trainee', 'Graduate entry configuring modules, documenting requirements and supporting UAT on SAP or Dynamics.', { priority: 20, eligibilityNote: 'Graduate ERP — not Graduate Software Developer building custom products from scratch.' }),
    r('Graduate CRM Consultant', 'entry_trainee', 'Graduate entry on Salesforce or Dynamics CRM configuration, data migration and user training.', { priority: 30, eligibilityNote: 'Graduate CRM — not Graduate Data Analyst or Marketing roles.' }),
    r('Trainee Business Systems Analyst (ERP)', 'entry_trainee', 'Supports process mapping, gap analysis and test scripts for UK ERP implementation projects.', { priority: 40, eligibilityNote: 'Trainee ERP analyst — not general Business Analyst in non-ERP domains.' }),
    r('Junior ERP Developer', 'junior', 'Develops extensions, reports and integrations on SAP, Oracle or Microsoft ERP under senior consultants.', { priority: 50, eligibilityNote: 'Junior ERP developer — not Junior Backend Developer for greenfield SaaS products.' }),
    r('Junior CRM Developer', 'junior', 'Builds Apex, plugins or Power Platform components for CRM customisation in UK consultancies.', { priority: 60, eligibilityNote: 'Junior CRM developer — not Frontend Web Developer or Mobile Developer.' }),
    r('Junior Dynamics 365 Consultant', 'junior', 'Configures Finance, Supply Chain or Customer Engagement modules with supervised client delivery.', { priority: 70, eligibilityNote: 'Junior Dynamics — not Cloud Engineer or DevOps roles.' }),
    r('Junior SAP Functional Consultant', 'junior', 'Supports SAP module configuration, testing and cutover activities on UK ERP programmes.', { priority: 80, eligibilityNote: 'Junior SAP functional — not SAP Basis Administrator-only roles without functional scope.' }),
    r('ERP Functional Consultant', 'practitioner', 'Owns module configuration, workshops and solution design for finance, HR or supply chain ERP.', { priority: 90, eligibilityNote: 'Mid-level ERP functional — not Enterprise Architect or general IT Project Manager.' }),
    r('CRM Functional Consultant', 'practitioner', 'Delivers Salesforce or Dynamics sales, service and marketing cloud configurations for UK clients.', { priority: 100, eligibilityNote: 'Mid-level CRM functional — not Digital Marketing Manager or Sales Operations roles.' }),
    r('ERP Technical Consultant', 'practitioner', 'Builds ABAP, X++, or integration middleware for ERP extensions and interfaces.', { priority: 110, eligibilityNote: 'ERP technical — not general Integration Developer outside ERP platforms.' }),
    r('CRM Technical Consultant', 'practitioner', 'Develops CRM integrations, custom APIs and automation flows for enterprise customer platforms.', { priority: 120, eligibilityNote: 'CRM technical — not Backend Developer for non-CRM product companies.' }),
    r('ERP Integration Specialist', 'practitioner', 'Designs and implements ERP interfaces with payroll, warehousing and third-party systems.', { priority: 130, eligibilityNote: 'ERP integration — not general Data Engineering or ETL roles without ERP context.' }),
    r('ERP Solutions Analyst (Mid-Level)', 'practitioner', 'Translates business requirements into ERP designs, fit-gap assessments and release plans.', { priority: 140, eligibilityNote: 'ERP solutions analysis — not Solutions Architect for greenfield cloud-native products.' }),
    r('Senior ERP Functional Consultant', 'senior', 'Leads complex module rollouts, blueprinting and client stakeholder management on UK ERP programmes.', { priority: 150, eligibilityNote: 'Senior ERP functional — not Senior Software Developer or Data Scientist.' }),
    r('Senior CRM Functional Consultant', 'senior', 'Owns CRM transformation workstreams, governance and multi-cloud CRM strategy for enterprises.', { priority: 160, eligibilityNote: 'Senior CRM functional — not Senior Product Manager without CRM platform expertise.' }),
    r('Senior ERP Technical Consultant', 'senior', 'Architects ERP customisations, performance tuning and upgrade paths for large UK estates.', { priority: 170, eligibilityNote: 'Senior ERP technical — not Senior Cloud Architect or DevOps Engineer.' }),
    r('Senior CRM Developer (Enterprise Platforms)', 'senior', 'Leads CRM development standards, CI/CD for metadata and complex customisations at scale.', { priority: 180, eligibilityNote: 'Senior CRM developer — not Senior Full Stack Developer in product SaaS companies.' }),
    r('Senior ERP Integration Engineer', 'senior', 'Owns integration patterns, API strategy and data synchronisation across ERP and satellite systems.', { priority: 190, eligibilityNote: 'Senior ERP integration — not Senior Data Engineer for analytics platforms only.' }),
    r('ERP Delivery Lead', 'lead_principal', 'Leads ERP workstreams, consultant teams and cutover planning for UK transformation programmes.', { priority: 210, eligibilityNote: 'ERP delivery lead — not generic Agile Delivery Lead without ERP domain.' }),
    r('CRM Practice Lead', 'lead_principal', 'Leads CRM consulting squad, methodology and quality for Salesforce or Dynamics practices.', { priority: 220, eligibilityNote: 'CRM practice lead — not Sales Director or Customer Success Lead.' }),
    r('ERP Technical Lead (Business Systems)', 'lead_principal', 'Technical leadership of ERP development, integrations and release management across modules.', { priority: 230, eligibilityNote: 'ERP technical lead — not Backend Team Lead in product engineering orgs.' }),
    r('ERP Solutions Architect', 'architect_specialist', 'Designs ERP landscape, module boundaries, integration topology and upgrade strategy.', { priority: 240, eligibilityNote: 'ERP solutions architecture — not bare Solutions Architect or Cloud Solutions Architect.' }),
    r('CRM Platform Architect', 'architect_specialist', 'Defines CRM org strategy, data model, security model and multi-org architecture for enterprises.', { priority: 250, eligibilityNote: 'CRM platform architecture — not Enterprise Architect for whole-of-IT strategy.' }),
    r('Business Systems Integration Architect (ERP)', 'architect_specialist', 'Architects middleware, eventing and master data flows between ERP, CRM and line-of-business apps.', { priority: 260, eligibilityNote: 'ERP integration architecture — not IoT or Cyber Security architecture roles.' }),
    r('ERP Programme Manager (Business Systems)', 'manager_head', 'Manages ERP implementation teams, vendors, budgets and benefits realisation for UK clients.', { priority: 270, eligibilityNote: 'ERP programme management — not IT Infrastructure Manager.' }),
    r('CRM Delivery Manager', 'manager_head', 'Owns CRM rollout delivery, release cadence and client relationship for consulting practices.', { priority: 280, eligibilityNote: 'CRM delivery management — not Marketing Operations Manager.' }),
    r('Head of ERP Practice', 'manager_head', 'Leads ERP consulting capability, hiring, partnerships and service offerings.', { priority: 290, eligibilityNote: 'Head of ERP — not Head of Finance or Head of IT Operations.' }),
    r('Director of Business Systems (ERP CRM)', 'director_executive', 'Executive leadership of ERP/CRM portfolio, vendor strategy and enterprise business applications.', { priority: 300, eligibilityNote: 'Director of business systems — not CTO or Director of Software Product Engineering.' }),
    r('Director of ERP Transformation', 'director_executive', 'Senior ownership of ERP modernisation, cloud migration and global template strategy.', { priority: 310, eligibilityNote: 'Director of ERP transformation — not Director of Cloud without ERP remit.' }),
  ],
}

const ENTERPRISE_ARCHITECTURE: SpecialismPack = {
  slug: 'enterprise-architecture',
  label: 'Enterprise Architecture',
  professionalBody: 'BCS, The Chartered Institute for IT',
  relatedBodies: ['The Open Group', 'AWS', 'Microsoft'],
  sources: ['prospects_it_consultant', 'national_careers_service_it_consultant', 'bcs_careers', 'open_group_togaf'],
  siblingSlugs: [
    'qa-software-testing',
    'game-development',
    'embedded-systems',
    'iot',
    'erp-crm-systems',
    'solutions-architecture',
    'blockchain',
    'other-it-technology'
  ],
  roles: [
    r('Graduate Enterprise Architecture Analyst', 'entry_trainee', 'Supports capability mapping, application inventories and architecture repository maintenance in UK enterprises.', { priority: 10, eligibilityNote: 'Graduate EA pathway — not Graduate Software Developer or coding-first entry roles.' }),
    r('Associate Enterprise Architect', 'entry_trainee', 'Junior architecture role documenting current state, standards compliance and roadmap inputs under chief architect.', { priority: 20, eligibilityNote: 'Associate EA — not Associate Solutions Architect focused on single-project delivery only.' }),
    r('Junior Technology Analyst (Enterprise Architecture)', 'entry_trainee', 'Analyses technology trends, vendor assessments and architecture decision records for EA teams.', { priority: 30, eligibilityNote: 'Junior EA analyst — not Junior Business Analyst in ERP or CRM projects.' }),
    r('Enterprise Architecture Apprentice', 'entry_trainee', 'Apprenticeship supporting architecture governance, modelling tools and stakeholder workshops.', { priority: 40, eligibilityNote: 'EA apprenticeship — not IT Support or Network Engineer apprenticeship routes.' }),
    r('Junior Enterprise Architect', 'junior', 'Develops architecture views, integration patterns and standards guidance on supervised EA workstreams.', { priority: 50, eligibilityNote: 'Junior EA — not Junior Solutions Architect owning end-to-end product solution design alone.' }),
    r('Junior Business Architect (Enterprise)', 'junior', 'Maps business capabilities, value streams and organisational alignment to technology strategy.', { priority: 60, eligibilityNote: 'Junior business architect EA — not HR Business Partner or Operations Manager roles.' }),
    r('Junior Data Architect (Enterprise Context)', 'junior', 'Supports enterprise data models, lineage and data governance within EA frameworks.', { priority: 70, eligibilityNote: 'Junior data architect in EA — not Data Engineer or Data Analyst delivery roles.' }),
    r('Junior Application Portfolio Analyst', 'junior', 'Maintains application rationalisation, TCO analysis and lifecycle data for EA repositories.', { priority: 80, eligibilityNote: 'Application portfolio EA — not IT Asset Manager without architecture accountability.' }),
    r('Enterprise Architect (Mid-Level)', 'practitioner', 'Owns domain architecture for business units, target states and transition roadmaps in UK orgs.', { priority: 90, eligibilityNote: 'Mid-level EA — not Mid-Level Solutions Architect on single programme delivery.' }),
    r('Business Architect (Enterprise)', 'practitioner', 'Aligns business strategy, operating models and technology investments at enterprise scale.', { priority: 100, eligibilityNote: 'Business architect EA — not Product Owner or Scrum-based delivery roles.' }),
    r('Information Architect (Enterprise)', 'practitioner', 'Designs enterprise information models, taxonomy and knowledge management architecture.', { priority: 110, eligibilityNote: 'Enterprise information architecture — not UX Information Architect for single products.' }),
    r('Security Architect (Enterprise)', 'practitioner', 'Defines enterprise security architecture, control frameworks and risk-aligned technology standards.', { priority: 120, eligibilityNote: 'Enterprise security architecture — not SOC Analyst or Penetration Tester roles.' }),
    r('Integration Architect (Enterprise)', 'practitioner', 'Sets enterprise integration standards, API governance and event-driven architecture patterns.', { priority: 130, eligibilityNote: 'Enterprise integration architecture — not ERP Integration Specialist module-only focus.' }),
    r('Technology Standards Architect', 'practitioner', 'Owns approved technology stacks, reference architectures and exception processes enterprise-wide.', { priority: 140, eligibilityNote: 'Technology standards EA — not DevOps Engineer implementing pipelines only.' }),
    r('Senior Enterprise Architect', 'senior', 'Leads strategic architecture for major domains, board-level narratives and transformation alignment.', { priority: 150, eligibilityNote: 'Senior EA — not Senior Solutions Architect without enterprise portfolio scope.' }),
    r('Senior Business Architect (Enterprise)', 'senior', 'Drives business capability evolution, operating model design and investment prioritisation.', { priority: 160, eligibilityNote: 'Senior business architect — not Management Consultant without technology architecture remit.' }),
    r('Senior Domain Architect (Enterprise)', 'senior', 'Owns architecture for finance, HR, supply chain or customer domains across application landscape.', { priority: 170, eligibilityNote: 'Senior domain EA — not ERP Functional Consultant without enterprise architecture accountability.' }),
    r('Senior Data Architect (Enterprise)', 'senior', 'Leads enterprise data strategy, master data architecture and analytics platform alignment.', { priority: 180, eligibilityNote: 'Senior enterprise data architect — not Senior Data Engineer building pipelines only.' }),
    r('Chief Domain Architect (Enterprise)', 'senior', 'Principal-level authority for a major enterprise domain with cross-programme architecture governance.', { priority: 190, eligibilityNote: 'Chief domain EA — not CTO or bare Solutions Architect title.' }),
    r('Enterprise Architecture Lead', 'lead_principal', 'Leads EA team delivery, review boards and architecture method adoption across UK enterprise.', { priority: 210, eligibilityNote: 'EA lead — not Engineering Team Lead for product development squads.' }),
    r('Lead Business Architect (Enterprise)', 'lead_principal', 'Directs business architecture practice, stakeholder engagement and capability roadmap execution.', { priority: 220, eligibilityNote: 'Lead business architect — not Programme Manager without architecture credentials.' }),
    r('Lead Technology Architect (Enterprise)', 'lead_principal', 'Leads technology architecture stream, standards enforcement and architecture community of practice.', { priority: 230, eligibilityNote: 'Lead technology EA — not Cloud Lead Engineer without enterprise governance scope.' }),
    r('Principal Enterprise Architect', 'architect_specialist', 'Principal authority on enterprise target architecture, divestiture and M&A technology integration.', { priority: 240, eligibilityNote: 'Principal EA — not Principal Software Engineer or Cloud Architect without EA remit.' }),
    r('Enterprise Reference Architect', 'architect_specialist', 'Maintains reference models, patterns library and architecture accelerators for the enterprise.', { priority: 250, eligibilityNote: 'Enterprise reference architecture — not IoT Solutions Architect or ERP Solutions Architect.' }),
    r('Enterprise Transformation Architect', 'architect_specialist', 'Architects large-scale transformation, cloud migration and operating model change at enterprise level.', { priority: 260, eligibilityNote: 'Enterprise transformation EA — not single-project Solutions Architect.' }),
    r('Head of Enterprise Architecture', 'manager_head', 'Manages EA function, talent, tooling and architecture review governance for UK enterprise.', { priority: 270, eligibilityNote: 'Head of EA — not Head of Engineering or Head of IT Operations.' }),
    r('Enterprise Architecture Manager', 'manager_head', 'Owns EA team delivery, stakeholder forums and architecture debt remediation programmes.', { priority: 280, eligibilityNote: 'EA manager — not IT Project Manager without architecture team leadership.' }),
    r('Chief Enterprise Architect', 'manager_head', 'Top enterprise architecture leader setting strategy, board engagement and architecture investment.', { priority: 290, eligibilityNote: 'Chief EA — not CTO unless explicitly dual-hatted with EA accountability.' }),
    r('Director of Enterprise Architecture', 'director_executive', 'Executive leadership of enterprise architecture capability, standards and digital transformation alignment.', { priority: 300, eligibilityNote: 'Director of EA — not Director of Solutions Architecture without enterprise portfolio scope.' }),
    r('VP Enterprise Architecture', 'director_executive', 'Senior executive shaping enterprise technology strategy, mergers integration and architecture operating model.', { priority: 310, eligibilityNote: 'VP EA — not VP Engineering for product R&D organisations only.' }),
  ],
}

const SOLUTIONS_ARCHITECTURE: SpecialismPack = {
  slug: 'solutions-architecture',
  label: 'Solutions Architecture',
  professionalBody: 'BCS, The Chartered Institute for IT',
  relatedBodies: ['The Open Group', 'AWS', 'Microsoft Azure'],
  sources: ['prospects_it_consultant', 'national_careers_service_it_consultant', 'bcs_careers', 'aws_solutions_architect'],
  siblingSlugs: [
    'qa-software-testing',
    'game-development',
    'embedded-systems',
    'iot',
    'erp-crm-systems',
    'enterprise-architecture',
    'blockchain',
    'other-it-technology'
  ],
  roles: [
    r('Graduate Solutions Analyst', 'entry_trainee', 'Supports solution design workshops, requirements traceability and architecture documentation on UK programmes.', { priority: 10, eligibilityNote: 'Graduate solutions analyst pathway — not Graduate Software Developer coding-first role.' }),
    r('Associate Solutions Architect', 'entry_trainee', 'Junior solutions role producing high-level designs, PoC support and integration sketches under lead SA.', { priority: 20, eligibilityNote: 'Associate SA — not Associate Enterprise Architect owning enterprise-wide standards.' }),
    r('Junior Technical Business Analyst (Solutions)', 'entry_trainee', 'Bridges business and technical teams with process flows, non-functional requirements and fit-gap analysis.', { priority: 30, eligibilityNote: 'Junior solutions BA — not ERP Functional Consultant or CRM-only analyst.' }),
    r('Solutions Architecture Apprentice', 'entry_trainee', 'Apprenticeship assisting solution assessments, cloud sizing and architecture diagramming on client projects.', { priority: 40, eligibilityNote: 'SA apprenticeship — not Cloud Engineer apprenticeship focused on operations only.' }),
    r('Junior Solutions Architect', 'junior', 'Develops solution designs for defined work packages including APIs, data flows and deployment views.', { priority: 50, eligibilityNote: 'Junior SA — not Junior Software Developer or Junior DevOps Engineer.' }),
    r('Junior Cloud Solutions Designer', 'junior', 'Creates cloud solution designs, landing zone sketches and security controls for UK client proposals.', { priority: 60, eligibilityNote: 'Junior cloud solutions — not Junior Cloud Engineer doing day-to-day ops only.' }),
    r('Junior Integration Solutions Analyst', 'junior', 'Analyses integration requirements, interface catalogues and middleware options for solution teams.', { priority: 70, eligibilityNote: 'Junior integration solutions — not Network Engineer or DBA roles.' }),
    r('Junior Pre-Sales Solutions Consultant', 'junior', 'Supports bid responses, solution demos and effort estimates for systems integrator or vendor teams.', { priority: 80, eligibilityNote: 'Junior pre-sales solutions — not Sales Executive without technical design involvement.' }),
    r('Solutions Architect (Mid-Level)', 'practitioner', 'Owns end-to-end solution design for programmes balancing functional, non-functional and delivery constraints.', { priority: 90, eligibilityNote: 'Mid-level SA — not Mid-Level Enterprise Architect for whole-of-enterprise governance.' }),
    r('Cloud Solutions Architect (Programmes)', 'practitioner', 'Designs workload migration, cloud-native and hybrid solutions for UK enterprise and public sector.', { priority: 100, eligibilityNote: 'Programme cloud SA — not Cloud Engineer or DevOps Engineer implementation role.' }),
    r('Application Solutions Architect', 'practitioner', 'Architects application modernisation, microservices decomposition and API-led integration solutions.', { priority: 110, eligibilityNote: 'Application SA — not Backend Developer or Full Stack Developer delivery role.' }),
    r('Data Solutions Architect', 'practitioner', 'Designs analytics, data platform and real-time data solutions for client or internal programmes.', { priority: 120, eligibilityNote: 'Data solutions SA — not Data Engineer building pipelines without architecture ownership.' }),
    r('Security Solutions Architect', 'practitioner', 'Embeds security controls, identity architecture and compliance into solution designs for UK clients.', { priority: 130, eligibilityNote: 'Security solutions SA — not Cyber Security Analyst in SOC operations.' }),
    r('Integration Solutions Architect (Programmes)', 'practitioner', 'Designs B2B integrations, event hubs and API gateways for multi-system solution delivery.', { priority: 140, eligibilityNote: 'Integration SA — not ERP Integration Specialist focused on SAP/Dynamics modules only.' }),
    r('Senior Solutions Architect', 'senior', 'Leads complex solution bids, architectural decision records and multi-team technical alignment.', { priority: 150, eligibilityNote: 'Senior SA — not Senior Enterprise Architect without programme solution delivery focus.' }),
    r('Senior Cloud Solutions Architect', 'senior', 'Owns large cloud transformation solution patterns, cost models and migration waves.', { priority: 160, eligibilityNote: 'Senior cloud SA — not Senior Cloud Engineer or SRE without design authority.' }),
    r('Senior Application Solutions Architect', 'senior', 'Leads application portfolio solution design, legacy retirement and target state applications.', { priority: 170, eligibilityNote: 'Senior application SA — not Senior Software Developer in product company squads.' }),
    r('Senior Integration Solutions Architect', 'senior', 'Sets integration solution standards, canonical models and partner ecosystem connectivity.', { priority: 180, eligibilityNote: 'Senior integration SA — not Senior Network Architect for datacentre LAN/WAN only.' }),
    r('Senior Pre-Sales Solutions Architect', 'senior', 'Leads technical win strategy, reference architectures and executive client workshops in bids.', { priority: 190, eligibilityNote: 'Senior pre-sales SA — not Account Manager without solution design accountability.' }),
    r('Solutions Architecture Lead', 'lead_principal', 'Leads SA team on major programme, quality of designs and architecture review ceremonies.', { priority: 210, eligibilityNote: 'SA lead — not Engineering Lead for product development teams.' }),
    r('Lead Cloud Solutions Architect', 'lead_principal', 'Directs cloud solution workstream, landing zones and multi-account architecture for programmes.', { priority: 220, eligibilityNote: 'Lead cloud SA — not Cloud Infrastructure Lead doing ops-only work.' }),
    r('Lead Integration Solutions Architect', 'lead_principal', 'Leads integration architecture squad across APIs, events and legacy connectivity.', { priority: 230, eligibilityNote: 'Lead integration SA — not Integration Developer lead without architecture remit.' }),
    r('Principal Solutions Architect', 'architect_specialist', 'Principal design authority for flagship programmes, complex non-functional requirements and risk.', { priority: 240, eligibilityNote: 'Principal SA — not Principal Enterprise Architect for enterprise-wide standards only.' }),
    r('Enterprise Solutions Architect (Programmes)', 'architect_specialist', 'Aligns programme solutions with enterprise standards while owning end-to-end solution integrity.', { priority: 250, eligibilityNote: 'Enterprise solutions SA — not Chief Enterprise Architect for whole organisation.' }),
    r('Digital Solutions Architect', 'architect_specialist', 'Architects digital channel, customer experience and omnichannel technology solutions.', { priority: 260, eligibilityNote: 'Digital SA — not UX Designer or Frontend Developer roles.' }),
    r('Head of Solutions Architecture', 'manager_head', 'Manages solutions architecture practice, hiring, methods and client delivery quality.', { priority: 270, eligibilityNote: 'Head of SA — not Head of Software Development or Head of Cloud Operations.' }),
    r('Solutions Architecture Manager', 'manager_head', 'Owns SA resourcing, career frameworks and architecture governance on consulting or product orgs.', { priority: 280, eligibilityNote: 'SA manager — not Project Manager without SA team leadership.' }),
    r('Chief Solutions Architect', 'manager_head', 'Top solutions architecture leader for organisation or major business unit technology programmes.', { priority: 290, eligibilityNote: 'Chief SA — not CTO unless explicitly combined with solutions architecture remit.' }),
    r('Director of Solutions Architecture', 'director_executive', 'Executive leadership of solutions architecture capability, key accounts and design excellence.', { priority: 300, eligibilityNote: 'Director of SA — not Director of Enterprise Architecture without programme solution focus.' }),
    r('VP Solutions Architecture', 'director_executive', 'Senior executive accountable for solution design standards, partner ecosystems and major bids.', { priority: 310, eligibilityNote: 'VP SA — not VP Engineering for product R&D without client solution accountability.' }),
  ],
}

const BLOCKCHAIN: SpecialismPack = {
  slug: 'blockchain',
  label: 'Blockchain',
  professionalBody: 'BCS, The Chartered Institute for IT',
  relatedBodies: ['Ethereum Foundation', 'Hyperledger', 'Web3 Foundation'],
  sources: ['prospects_software_developer', 'national_careers_service_software_developer', 'bcs_careers', 'tech_nation_skills'],
  siblingSlugs: [
    'qa-software-testing',
    'game-development',
    'embedded-systems',
    'iot',
    'erp-crm-systems',
    'enterprise-architecture',
    'solutions-architecture',
    'other-it-technology'
  ],
  roles: [
    r('Blockchain Apprentice (Distributed Ledger)', 'entry_trainee', 'Apprenticeship learning smart contract basics, wallet security and DLT fundamentals in UK Web3 or fintech teams.', { priority: 10, eligibilityNote: 'Blockchain apprenticeship — not general Software Development or Cyber Security apprenticeship.' }),
    r('Graduate Blockchain Developer', 'entry_trainee', 'Graduate entry building smart contracts, dApp frontends and test networks under senior blockchain engineers.', { priority: 20, eligibilityNote: 'Graduate blockchain — not Graduate Backend Developer without DLT exposure.' }),
    r('Junior Smart Contract Developer', 'entry_trainee', 'Develops and tests Solidity or Rust smart contracts with guidance on security patterns and gas optimisation.', { priority: 30, eligibilityNote: 'Junior smart contract — not Junior Software Developer in non-blockchain products.' }),
    r('Trainee Web3 Developer', 'entry_trainee', 'Supports dApp integration, wallet connectivity and blockchain API usage on supervised projects.', { priority: 40, eligibilityNote: 'Trainee Web3 — not Frontend Web Developer without wallet/chain integration.' }),
    r('Junior Blockchain Engineer', 'junior', 'Implements node configuration, indexing services and backend integrations with Ethereum or Hyperledger.', { priority: 50, eligibilityNote: 'Junior blockchain engineer — not Junior DevOps or Junior Cloud Engineer.' }),
    r('Junior DLT Developer', 'junior', 'Builds permissioned ledger solutions, chaincode and consortium network components for UK enterprises.', { priority: 60, eligibilityNote: 'Junior DLT — not Junior Database Administrator or ERP Developer.' }),
    r('Junior DeFi Protocol Developer', 'junior', 'Contributes to decentralised finance protocol modules, testing and governance tooling under senior team.', { priority: 70, eligibilityNote: 'Junior DeFi — not FinCrime Analyst or traditional Banking Software roles without DLT.' }),
    r('Junior NFT Platform Engineer', 'junior', 'Develops minting flows, metadata storage and marketplace integrations for digital asset platforms.', { priority: 80, eligibilityNote: 'Junior NFT platform — not Digital Marketing or Content Creator roles.' }),
    r('Blockchain Developer', 'practitioner', 'Owns smart contract features, upgrade patterns and on-chain/off-chain integration for UK products.', { priority: 90, eligibilityNote: 'Mid-level blockchain — not Mid-Level Backend Developer without ledger expertise.' }),
    r('Smart Contract Engineer (Blockchain)', 'practitioner', 'Designs secure contract architecture, audit remediation and formal verification collaboration.', { priority: 100, eligibilityNote: 'Smart contract engineering — not Cyber Penetration Tester without development remit.' }),
    r('Web3 Full Stack Developer', 'practitioner', 'Delivers end-to-end dApps combining wallet UX, indexers and smart contract backends.', { priority: 110, eligibilityNote: 'Web3 full stack — not Full Stack Developer for traditional SaaS without chain components.' }),
    r('Enterprise Blockchain Developer', 'practitioner', 'Builds private DLT solutions for supply chain, identity or finance use cases in UK enterprises.', { priority: 120, eligibilityNote: 'Enterprise blockchain — not ERP Developer or CRM Developer roles.' }),
    r('Blockchain Integration Engineer', 'practitioner', 'Integrates DLT with ERP, payment rails and identity systems via APIs and oracles.', { priority: 130, eligibilityNote: 'Blockchain integration — not general Integration Developer outside DLT context.' }),
    r('Senior Blockchain Developer', 'senior', 'Leads protocol modules, security reviews and architectural decisions for production blockchain systems.', { priority: 150, eligibilityNote: 'Senior blockchain — not Senior Software Developer without DLT specialisation.' }),
    r('Senior Smart Contract Engineer', 'senior', 'Owns contract standards, threat modelling and audit cycles for high-value on-chain assets.', { priority: 160, eligibilityNote: 'Senior smart contract — not Senior Cyber Security Engineer in corporate IT only.' }),
    r('Senior Web3 Engineer', 'senior', 'Sets Web3 engineering practices, tooling and reliability for consumer or institutional dApp products.', { priority: 170, eligibilityNote: 'Senior Web3 — not Senior Frontend Developer without blockchain backend integration.' }),
    r('Senior Enterprise DLT Engineer', 'senior', 'Leads Hyperledger or Corda solutions, network governance and production operations for consortia.', { priority: 180, eligibilityNote: 'Senior enterprise DLT — not Senior Cloud Architect without ledger platform focus.' }),
    r('Senior Blockchain Security Engineer', 'senior', 'Specialises in smart contract audits, key management and blockchain-specific threat mitigation.', { priority: 190, eligibilityNote: 'Blockchain security — not SOC Analyst or GRC Consultant without engineering depth.' }),
    r('Blockchain Engineering Lead', 'lead_principal', 'Leads blockchain squad delivery, code review and protocol roadmap for UK Web3 or enterprise DLT.', { priority: 210, eligibilityNote: 'Blockchain lead — not Engineering Lead in non-blockchain product teams.' }),
    r('Smart Contract Team Lead', 'lead_principal', 'Directs smart contract developers, release processes and mainnet deployment governance.', { priority: 220, eligibilityNote: 'Smart contract lead — not Backend Team Lead for traditional APIs only.' }),
    r('Web3 Engineering Lead', 'lead_principal', 'Leads Web3 product engineering across contracts, indexers and client applications.', { priority: 230, eligibilityNote: 'Web3 lead — not Mobile Development Lead or Frontend Lead without chain integration.' }),
    r('Blockchain Solutions Architect', 'architect_specialist', 'Designs DLT solution topology, consensus choices, tokenomics integration and enterprise fit.', { priority: 240, eligibilityNote: 'Blockchain SA — not bare Solutions Architect or Cloud Solutions Architect without DLT.' }),
    r('Smart Contract Architect (Blockchain)', 'architect_specialist', 'Defines contract upgradeability, proxy patterns and security architecture for on-chain systems.', { priority: 250, eligibilityNote: 'Smart contract architecture — not Application Architect for non-blockchain systems.' }),
    r('Enterprise DLT Architect', 'architect_specialist', 'Architects permissioned networks, identity models and interoperability for UK enterprise blockchain.', { priority: 260, eligibilityNote: 'Enterprise DLT architect — not Enterprise Architect for whole-of-IT without DLT focus.' }),
    r('Blockchain Engineering Manager', 'manager_head', 'Manages blockchain engineering teams, vendor partnerships and delivery for DLT products.', { priority: 270, eligibilityNote: 'Blockchain engineering manager — not IT Operations Manager.' }),
    r('Head of Blockchain Engineering', 'manager_head', 'Leads blockchain practice, R&D investment and engineering standards for UK crypto or fintech org.', { priority: 280, eligibilityNote: 'Head of blockchain — not Head of Software Development for non-DLT products.' }),
    r('Web3 Product Engineering Manager', 'manager_head', 'Owns Web3 product engineering roadmap, squad structure and mainnet launch governance.', { priority: 290, eligibilityNote: 'Web3 product engineering manager — not Product Manager without engineering team leadership.' }),
    r('Director of Blockchain', 'director_executive', 'Executive leadership of blockchain strategy, portfolio and organisational DLT capability.', { priority: 300, eligibilityNote: 'Director of blockchain — not Director of IT without DLT product or platform remit.' }),
    r('Director of Web3 Engineering', 'director_executive', 'Senior leadership of Web3 engineering organisation, partnerships and regulatory-aligned delivery.', { priority: 310, eligibilityNote: 'Director of Web3 — not Director of Software Development for traditional enterprise apps.' }),
  ],
}

const OTHER_IT_TECHNOLOGY: SpecialismPack = {
  slug: 'other-it-technology',
  label: 'Other IT & Technology',
  professionalBody: 'BCS, The Chartered Institute for IT',
  relatedBodies: ['TechSkills', 'CompTIA', 'Microsoft'],
  sources: ['prospects_it_technician', 'national_careers_service_it_technician', 'bcs_careers', 'tech_nation_skills'],
  siblingSlugs: [
    'qa-software-testing',
    'game-development',
    'embedded-systems',
    'iot',
    'erp-crm-systems',
    'enterprise-architecture',
    'solutions-architecture',
    'blockchain'
  ],
  roles: [
    r('IT & Technology Apprentice (Generalist)', 'entry_trainee', 'Broad apprenticeship rotating across support, projects and digital skills for undecided IT pathways.', { priority: 10, eligibilityNote: 'Generalist IT apprenticeship — use when pathway spans multiple specialisms not covered elsewhere.' }),
    r('Graduate IT Analyst (Generalist)', 'entry_trainee', 'Graduate rotation or analyst role spanning projects, vendors and technology assessment without single specialism.', { priority: 20, eligibilityNote: 'Generalist IT analyst — not Graduate Software Developer, Data Analyst or Cyber roles specifically.' }),
    r('Junior Digital Transformation Analyst', 'entry_trainee', 'Supports change programmes, process digitisation and technology adoption across business units.', { priority: 30, eligibilityNote: 'Digital transformation generalist — not ERP Consultant or Solutions Architect entry.' }),
    r('Trainee IT Project Coordinator', 'entry_trainee', 'Coordinates project admin, RAID logs and stakeholder comms for mixed technology programmes.', { priority: 40, eligibilityNote: 'IT project coordinator — not Scrum Master or Product Owner specialist roles.' }),
    r('Junior IT Business Analyst (General)', 'junior', 'Gathers requirements, maps processes and supports UAT across heterogeneous technology projects.', { priority: 50, eligibilityNote: 'General IT BA — not ERP Functional Consultant or CRM Functional Consultant.' }),
    r('Junior Technology Consultant (Generalist)', 'junior', 'Delivers small technology assessments, vendor comparisons and implementation support broadly.', { priority: 60, eligibilityNote: 'General technology consultant — not Cloud Engineer or DevOps Engineer specialist.' }),
    r('Junior IT Governance Analyst', 'junior', 'Supports policy compliance, risk registers and control testing for IT governance functions.', { priority: 70, eligibilityNote: 'IT governance — not Cyber Security Analyst in SOC or GRC-only without IT ops context.' }),
    r('Junior Digital Product Analyst (Technology)', 'junior', 'Analyses product metrics, backlog inputs and cross-functional delivery for digital products.', { priority: 80, eligibilityNote: 'Digital product analyst — not Data Scientist or UX Researcher specialist roles.' }),
    r('IT Business Analyst (Generalist)', 'practitioner', 'Owns requirements and solution alignment for programmes spanning multiple technology domains.', { priority: 90, eligibilityNote: 'Mid-level general IT BA — not domain-specific ERP, CRM or Data Analytics BA.' }),
    r('Technology Consultant (Generalist)', 'practitioner', 'Advises clients on technology options, roadmaps and delivery approaches without single-vendor specialism.', { priority: 100, eligibilityNote: 'General technology consultant — not Solutions Architect or Enterprise Architect titles.' }),
    r('IT Portfolio Analyst', 'practitioner', 'Manages project portfolios, benefits tracking and investment prioritisation for IT functions.', { priority: 110, eligibilityNote: 'IT portfolio — not Project Manager owning single project delivery only.' }),
    r('Digital Transformation Consultant (General)', 'practitioner', 'Leads workshops, change impact and technology enablement for organisational transformation.', { priority: 120, eligibilityNote: 'General digital transformation — not single-stack Cloud or ERP transformation specialist.' }),
    r('IT Vendor Manager (Technology)', 'practitioner', 'Manages vendor relationships, SLAs and contract performance for diverse technology suppliers.', { priority: 130, eligibilityNote: 'IT vendor management — not Procurement Manager without technology accountability.' }),
    r('Technology Risk Analyst (IT)', 'practitioner', 'Assesses technology risks, control gaps and remediation for enterprise risk functions.', { priority: 140, eligibilityNote: 'Technology risk — not dedicated Cyber Penetration Tester or SOC roles.' }),
    r('Senior IT Business Analyst (Generalist)', 'senior', 'Leads complex cross-domain requirements, stakeholder negotiation and delivery alignment.', { priority: 150, eligibilityNote: 'Senior general BA — not Senior ERP Functional Consultant or Senior Data Analyst.' }),
    r('Senior Technology Consultant (Generalist)', 'senior', 'Owns client advisory, multi-tower proposals and executive technology recommendations.', { priority: 160, eligibilityNote: 'Senior general consultant — not Senior Solutions Architect or Senior Cloud Engineer.' }),
    r('Senior Digital Transformation Lead (General)', 'senior', 'Leads transformation workstreams combining people, process and multi-vendor technology change.', { priority: 170, eligibilityNote: 'Senior general transformation — not Director-level; not ERP-only transformation lead.' }),
    r('Senior IT Portfolio Manager', 'senior', 'Governs portfolio prioritisation, capacity planning and benefits realisation across IT investments.', { priority: 180, eligibilityNote: 'Senior IT portfolio — not Programme Manager for single implementation.' }),
    r('Senior IT Governance Manager', 'senior', 'Owns IT policies, audit remediation and control frameworks across technology estate.', { priority: 190, eligibilityNote: 'Senior IT governance — not CISO or Cyber Security Manager specialist roles.' }),
    r('IT Delivery Lead (Generalist)', 'lead_principal', 'Leads mixed technology delivery teams across support, projects and vendor coordination.', { priority: 210, eligibilityNote: 'General IT delivery lead — not DevOps Lead or QA Lead specialist roles.' }),
    r('Digital Transformation Lead (General IT)', 'lead_principal', 'Directs cross-functional transformation initiatives spanning multiple technology specialisms.', { priority: 220, eligibilityNote: 'General transformation lead — not Cloud Transformation Lead or ERP Delivery Lead only.' }),
    r('Technology Practice Lead (Generalist)', 'lead_principal', 'Leads consulting or internal practice covering broad technology advisory and delivery.', { priority: 230, eligibilityNote: 'General practice lead — not Cyber Practice Lead or Cloud Practice Lead specifically.' }),
    r('Generalist IT Architect', 'architect_specialist', 'Provides architecture guidance across mixed estates when no single specialism architect applies.', { priority: 240, eligibilityNote: 'Generalist IT architect — not Enterprise Architect, Solutions Architect or Cloud Architect specialists.' }),
    r('Digital Platform Architect (General IT)', 'architect_specialist', 'Architects heterogeneous digital platforms combining multiple vendors and integration patterns.', { priority: 250, eligibilityNote: 'General digital platform — not IoT Platform Architect or CRM Platform Architect.' }),
    r('Transformation Technology Architect', 'architect_specialist', 'Designs technology enablers for broad transformation when solutions span multiple domains.', { priority: 260, eligibilityNote: 'Transformation architect general — not ERP Solutions Architect or Blockchain Solutions Architect.' }),
    r('IT Operations Manager (Generalist)', 'manager_head', 'Manages mixed IT operations spanning support, projects and vendor services without single infra specialism.', { priority: 270, eligibilityNote: 'General IT ops manager — not DevOps Manager or Network Manager specialist.' }),
    r('Head of IT (Generalist Organisation)', 'manager_head', 'Leads IT function for SME or unit with diverse technology responsibilities.', { priority: 280, eligibilityNote: 'Head of IT generalist — not Head of Cloud, Head of Cyber or Head of Data specifically.' }),
    r('Technology Programme Manager (General)', 'manager_head', 'Manages multi-tower technology programmes without single ERP, cloud or cyber focus.', { priority: 290, eligibilityNote: 'General technology PM — not ERP Programme Manager or Cloud Programme Manager only.' }),
    r('Director of IT (Generalist)', 'director_executive', 'Executive leadership of IT for organisations with broad undifferentiated technology needs.', { priority: 300, eligibilityNote: 'Director of IT generalist — not Director of Software Development or Director of Cyber.' }),
    r('Director of Digital & Technology (General)', 'director_executive', 'Senior leadership spanning digital, IT and transformation when specialism-specific director titles do not fit.', { priority: 310, eligibilityNote: 'General digital & technology director — fallback specialism for multidisciplinary IT leadership.' }),
  ],
}

export const SPECIALIST_PACKS: SpecialismPack[] = [
  QA_SOFTWARE_TESTING,
  GAME_DEVELOPMENT,
  EMBEDDED_SYSTEMS,
  IOT,
  ERP_CRM_SYSTEMS,
  ENTERPRISE_ARCHITECTURE,
  SOLUTIONS_ARCHITECTURE,
  BLOCKCHAIN,
  OTHER_IT_TECHNOLOGY,
]
