import type {
  AiGroupSuggestion,
  CommunityStats,
  CurrentUserFeedProfile,
  FeedGroup,
  FeedPost,
  FeedPrompt,
  SuggestedFriend,
  TrendingTopic,
} from './types'
import type { PostUserReactions } from './reactions/types'

function demoReactions(support: number, user: Partial<PostUserReactions> = {}) {
  const boost = Math.max(0, Math.round(support * 0.25))
  const useful = Math.max(0, Math.round(support * 0.2))
  const supportCount = Math.max(0, support - boost - useful)
  return {
    reactionCounts: { boost, support: supportCount, useful },
    userReactions: { boost: false, support: false, useful: false, ...user },
  }
}

export const CURRENT_USER: CurrentUserFeedProfile = {
  name: 'You',
  initials: 'YO',
  careerPath: 'Warehouse & Logistics',
  careerScore: 72,
}

export const COMMUNITY_STATS: CommunityStats = {
  activeToday: 847,
  postsToday: 124,
  newMembers: 38,
  successStoriesWeek: 56,
}

export const FEED_PROMPTS: FeedPrompt[] = [
  { id: 'p1', text: 'Share a win from your job search or first week at work.', action: 'Share a win', postType: 'success_story' },
  { id: 'p2', text: 'What should I do next in my UK career journey?', action: 'Ask for help', postType: 'question' },
  { id: 'p3', text: 'I am offering a local service or project — who is interested?', action: 'Add opportunity', postType: 'opportunity' },
  { id: 'p4', text: 'Working on a side project and looking for collaborators.', action: 'Share project', postType: 'project' },
]

/** 8+ realistic career community posts — shown immediately on page load */
export const SAMPLE_POSTS: FeedPost[] = [
  {
    id: 'post-1',
    authorName: 'Ahmed',
    authorInitials: 'AH',
    authorBadge: 'Warehouse Path',
    authorColor: 'from-amber-600/50 to-orange-500/30',
    groupName: 'JobAZ Success Stories',
    text: 'Got my first warehouse interview after updating my CV on JobAZ. Thank you everyone.',
    timeAgo: '32m ago',
    category: 'success',
    isFriend: true,
    isFromMyGroup: true,
    ...demoReactions(47),
    saved: false,
    comments: [
      { id: 'c1', authorName: 'Sara M.', text: 'So proud of you Ahmed! Which company was it?', timeAgo: '18m ago' },
      { id: 'c2', authorName: 'James T.', text: 'The CV builder keywords section really helped me too. Good luck!', timeAgo: '12m ago' },
    ],
  },
  {
    id: 'post-2',
    authorName: 'Sara',
    authorInitials: 'SA',
    authorBadge: 'Customer Service',
    authorColor: 'from-pink-600/40 to-rose-500/30',
    groupName: 'Newcastle Job Seekers',
    text: 'Does anyone know beginner-friendly jobs in Newcastle with flexible shifts?',
    timeAgo: '1h ago',
    category: 'question',
    isFriend: true,
    isFromMyGroup: true,
    ...demoReactions(19),
    saved: true,
    comments: [
      { id: 'c3', authorName: 'Priya K.', text: 'Retail at Eldon Square often hires part-time. Agencies on Pilgrim Street are worth a call.', timeAgo: '45m ago' },
      { id: 'c4', authorName: 'Omar H.', text: 'Try hospitality — less CV pressure when starting out.', timeAgo: '30m ago' },
    ],
  },
  {
    id: 'post-3',
    authorName: 'Omar',
    authorInitials: 'OM',
    authorBadge: 'Driving & Logistics',
    authorColor: 'from-blue-600/40 to-cyan-500/30',
    groupName: 'UK Drivers Network',
    text: 'Uber demand was crazy this weekend in Manchester.',
    timeAgo: '2h ago',
    category: 'job-tip',
    isFriend: true,
    isFromMyGroup: false,
    ...demoReactions(63, { support: true }),
    saved: false,
    comments: [
      { id: 'c5', authorName: 'Daniel W.', text: 'Same in Birmingham. Airport runs are worth it early mornings.', timeAgo: '1h ago' },
    ],
  },
  {
    id: 'post-4',
    authorName: 'Maya',
    authorInitials: 'MY',
    authorBadge: 'Junior IT',
    authorColor: 'from-violet-600/50 to-indigo-500/30',
    groupName: 'Junior Tech & IT Support',
    text: 'Passed my Google IT Support certificate today.',
    timeAgo: '3h ago',
    category: 'success',
    isFriend: false,
    isFromMyGroup: false,
    media: { type: 'image', label: 'Certificate celebration photo' },
    ...demoReactions(89),
    saved: false,
    comments: [
      { id: 'c6', authorName: 'Alex P.', text: 'Congratulations! Which modules were hardest?', timeAgo: '2h ago' },
      { id: 'c7', authorName: 'Fatima K.', text: 'Inspiring — I want to move into IT too.', timeAgo: '1h ago' },
    ],
  },
  {
    id: 'post-5',
    authorName: 'Anonymous',
    authorInitials: '?',
    authorBadge: 'Career seeker',
    authorColor: 'from-slate-600/50 to-slate-500/30',
    text: 'I struggle with interview anxiety. My mind goes blank even when I know the answers. Any advice from people who overcame this?',
    timeAgo: '5h ago',
    category: 'interview',
    isFriend: false,
    isFromMyGroup: false,
    visibility: 'anonymous',
    ...demoReactions(54),
    saved: false,
    comments: [
      { id: 'c8', authorName: 'Community member', text: "You're not alone. I practice with JobAZ interview coach for 15 min daily — it helped more than I expected.", timeAgo: '4h ago' },
      { id: 'c9', authorName: 'Sara M.', text: 'Write 3 stories on paper before the interview. STAR method saved me.', timeAgo: '3h ago' },
    ],
  },
  {
    id: 'post-6',
    authorName: 'Community moderator',
    authorInitials: 'JZ',
    authorBadge: 'Community team',
    authorColor: 'from-emerald-600/40 to-teal-500/30',
    groupName: 'Warehouse & Logistics UK',
    text: 'New warehouse jobs added today.',
    timeAgo: '6h ago',
    category: 'moderator',
    isFriend: false,
    isFromMyGroup: true,
    isModerator: true,
    ...demoReactions(112),
    saved: true,
    comments: [
      { id: 'c10', authorName: 'Ahmed R.', text: 'Thanks — applied to two already!', timeAgo: '5h ago' },
    ],
  },
  {
    id: 'post-7',
    authorName: 'Fatima K.',
    authorInitials: 'FK',
    authorBadge: 'Customer Service Path',
    authorColor: 'from-fuchsia-600/40 to-purple-500/30',
    groupName: 'CV Advice Circle',
    text: 'Before vs after using JobAZ CV builder. My old CV was one block of text — now recruiters actually reply. Sharing in case it helps someone else starting out.',
    timeAgo: '8h ago',
    category: 'cv',
    isFriend: true,
    isFromMyGroup: false,
    media: { type: 'cv-comparison', label: 'CV before / after' },
    ...demoReactions(76),
    saved: false,
    comments: [
      { id: 'c11', authorName: 'Maya L.', text: 'The difference is huge. What template did you use?', timeAgo: '7h ago' },
    ],
  },
  {
    id: 'post-8',
    authorName: 'James T.',
    authorInitials: 'JT',
    authorBadge: 'Warehouse Supervisor',
    authorColor: 'from-orange-600/40 to-amber-500/30',
    groupName: 'JobAZ Success Stories',
    text: 'First day at my new warehouse supervisor role today. Six months ago I was unemployed. This community kept me going — especially the interview tips thread.',
    timeAgo: '10h ago',
    category: 'success',
    isFriend: false,
    isFromMyGroup: true,
    media: { type: 'image', label: 'First day at work — safety boots and smile' },
    ...demoReactions(134),
    saved: false,
    comments: [
      { id: 'c12', authorName: 'Ahmed R.', text: 'This gives me hope. Well done James!', timeAgo: '9h ago' },
      { id: 'c13', authorName: 'Omar H.', text: 'Legend. Enjoy day one!', timeAgo: '8h ago' },
    ],
  },
  {
    id: 'post-9',
    authorName: 'Priya S.',
    authorInitials: 'PS',
    authorBadge: 'Healthcare Assistant',
    authorColor: 'from-teal-600/40 to-emerald-500/30',
    groupName: 'Healthcare Assistant Careers',
    text: 'Quick tip: many care homes accept applicants without prior UK care experience if you show reliability and basic English. DBS can take 2–3 weeks — start early.',
    timeAgo: '12h ago',
    category: 'job-tip',
    isFriend: false,
    isFromMyGroup: false,
    ...demoReactions(41),
    saved: false,
    comments: [],
  },
]

export const SAMPLE_GROUPS: FeedGroup[] = [
  {
    id: 'g-drivers',
    slug: 'uk-drivers-network',
    name: 'UK Drivers Network',
    description: 'Delivery, taxi, and logistics drivers sharing routes, licences, and hiring tips.',
    memberCount: 2840,
    category: 'Transport',
    joined: false,
    icon: '🚗',
    activityLevel: 'High',
    postsToday: 18,
  },
  {
    id: 'g-warehouse',
    slug: 'warehouse-logistics-uk',
    name: 'Warehouse & Logistics UK',
    description: 'Entry roles, shift patterns, and agency advice for warehouse work.',
    memberCount: 5120,
    category: 'Logistics',
    joined: true,
    icon: '📦',
    activityLevel: 'Very high',
    postsToday: 34,
  },
  {
    id: 'g-english',
    slug: 'beginner-english-support',
    name: 'Beginner English Support',
    description: 'Workplace English, simple roles, and interview confidence for new speakers.',
    memberCount: 4200,
    category: 'Language',
    joined: false,
    icon: '💬',
    activityLevel: 'High',
    postsToday: 22,
  },
  {
    id: 'g-health',
    slug: 'healthcare-assistant-careers',
    name: 'Healthcare Assistant Careers',
    description: 'Care roles, training pathways, and DBS guidance across the UK.',
    memberCount: 2340,
    category: 'Healthcare',
    joined: false,
    icon: '🏥',
    activityLevel: 'Medium',
    postsToday: 9,
  },
  {
    id: 'g-success',
    slug: 'jobaz-success-stories',
    name: 'JobAZ Success Stories',
    description: 'Wins, first interviews, and career milestones from the community.',
    memberCount: 3890,
    category: 'Motivation',
    joined: true,
    icon: '🌟',
    activityLevel: 'Very high',
    postsToday: 28,
  },
  {
    id: 'g-newcastle',
    slug: 'newcastle-job-seekers',
    name: 'Newcastle Job Seekers',
    description: 'Local roles, agencies, and advice for the North East.',
    memberCount: 1120,
    category: 'Local',
    joined: true,
    icon: '📍',
    activityLevel: 'Active now',
    postsToday: 15,
  },
  {
    id: 'g-cs',
    slug: 'customer-service-careers',
    name: 'Customer Service Careers',
    description: 'Retail, call centre, and front-of-house opportunities.',
    memberCount: 2670,
    category: 'Service',
    joined: false,
    icon: '🎧',
    activityLevel: 'High',
    postsToday: 12,
  },
  {
    id: 'g-tech',
    slug: 'junior-tech-it-support',
    name: 'Junior Tech & IT Support',
    description: 'First IT roles, certifications, and portfolio tips.',
    memberCount: 1890,
    category: 'Technology',
    joined: false,
    icon: '💻',
    activityLevel: 'Medium',
    postsToday: 8,
  },
]

export const SUGGESTED_FRIENDS: SuggestedFriend[] = [
  { id: 'f1', name: 'Ahmed', careerPath: 'Warehouse Path', mutualGroup: 'Warehouse & Logistics UK', initials: 'AH', color: 'from-amber-500/40 to-orange-500/30', requestSent: false },
  { id: 'f2', name: 'Sara', careerPath: 'Customer Service', mutualGroup: 'Newcastle Job Seekers', initials: 'SA', color: 'from-pink-500/40 to-rose-500/30', requestSent: false },
  { id: 'f3', name: 'Omar', careerPath: 'Driving & Logistics', mutualGroup: 'UK Drivers Network', initials: 'OM', color: 'from-blue-500/40 to-cyan-500/30', requestSent: false },
  { id: 'f4', name: 'Maya', careerPath: 'Junior Tech', mutualGroup: 'Junior Tech & IT Support', initials: 'MY', color: 'from-violet-500/40 to-indigo-500/30', requestSent: false },
  { id: 'f5', name: 'Fatima', careerPath: 'Customer Service', mutualGroup: 'JobAZ Success Stories', initials: 'FK', color: 'from-fuchsia-500/40 to-purple-500/30', requestSent: false },
]

export const AI_GROUP_SUGGESTIONS: AiGroupSuggestion[] = [
  { groupId: 'g-warehouse', reason: 'Your profile shows interest in practical full-time roles.' },
  { groupId: 'g-english', reason: 'Helps with workplace communication and interview confidence.' },
  { groupId: 'g-drivers', reason: 'Good for flexible work and delivery/taxi paths.' },
  { groupId: 'g-newcastle', reason: 'Active local community near your search area.' },
]

export const TRENDING_TOPICS: TrendingTopic[] = [
  { id: 't1', label: '#SeasonalHiring', posts: 128 },
  { id: 't2', label: '#InterviewConfidence', posts: 94 },
  { id: 't3', label: '#CVImprovement', posts: 76 },
  { id: 't4', label: '#WarehouseShifts', posts: 61 },
  { id: 't5', label: '#FirstInterview', posts: 48 },
]

export const COMPOSER_GROUPS = [
  'Public Pulse',
  'Warehouse & Logistics UK',
  'JobAZ Success Stories',
  'Newcastle Job Seekers',
  'Beginner English Support',
  'UK Drivers Network',
  'Customer Service Careers',
]
