/**
 * UK side-income catalog — opportunities, qualifications, long-term streams.
 * Affiliate fields are placeholders only (null until partnerships are wired).
 */

import type {
  EarningsBoostQualification,
  ImmediateOpportunity,
  LongTermSideIncome,
} from './types'

type OpportunityDef = Omit<
  ImmediateOpportunity,
  | 'whyMatch'
  | 'monthlyEstimate'
  | 'matchScore'
  | 'matchReasons'
  | 'startTimeline'
  | 'difficulty'
  | 'hiringDemand'
> & {
  hourlyLow: number
  hourlyHigh: number
  skillTags: string[]
  scheduleFit: string[]
  profiles?: string[]
  minHours?: 'under_10' | '10_20' | '20_plus'
  londonBoost?: boolean
  /** Catalog defaults — personalised in the decision engine where needed */
  startSpeed: 'today' | 'this_week' | 'two_weeks' | 'after_course'
  entryDifficulty: 'easy' | 'medium' | 'competitive'
  demand: 'very_high' | 'high' | 'medium'
  noExperienceRequired?: boolean
}

export const SIDE_SKILL_OPTIONS = [
  { value: 'driving', label: 'Driving / Delivery' },
  { value: 'customer_service', label: 'Customer Service' },
  { value: 'hospitality', label: 'Hospitality / Events' },
  { value: 'retail', label: 'Retail' },
  { value: 'warehouse', label: 'Warehouse' },
  { value: 'administration', label: 'Administration' },
  { value: 'writing', label: 'Writing' },
  { value: 'teaching', label: 'Teaching / Tutoring' },
  { value: 'tech', label: 'IT / Tech' },
  { value: 'creative', label: 'Creative / Design' },
  { value: 'photography', label: 'Photography / Video' },
  { value: 'languages', label: 'Languages / Translation' },
  { value: 'care', label: 'Care / Support' },
  { value: 'cleaning', label: 'Cleaning' },
  { value: 'security', label: 'Security' },
  { value: 'trades', label: 'Trades / Handyman' },
  { value: 'sales', label: 'Sales' },
  { value: 'marketing', label: 'Marketing / Social Media' },
  { value: 'general', label: 'General / Open to anything' },
] as const

export const OPPORTUNITY_CATALOG: OpportunityDef[] = [
  {
    id: 'delivery_driver',
    title: 'Delivery Driver',
    entryRequirements: ['UK driving licence', 'Own vehicle or van (some roles provide vans)', 'Right to work'],
    flexibility: 'Evenings, weekends, and flexible shifts common',
    hourlyPay: '£11–£16/hr',
    hourlyLow: 11,
    hourlyHigh: 16,
    skillTags: ['driving', 'general'],
    scheduleFit: ['evenings_weekends', 'flexible', 'weekdays'],
    startSpeed: 'this_week',
    entryDifficulty: 'easy',
    demand: 'very_high',
  },
  {
    id: 'uber_eats',
    title: 'Uber Eats / Deliveroo Rider',
    entryRequirements: ['Bike, scooter, or car', 'Smartphone', 'Right to work', 'Age 18+'],
    flexibility: 'Fully flexible — work when you want',
    hourlyPay: '£10–£15/hr (incl. tips)',
    hourlyLow: 10,
    hourlyHigh: 15,
    skillTags: ['driving', 'general'],
    scheduleFit: ['evenings_weekends', 'flexible'],
    londonBoost: true,
    startSpeed: 'today',
    entryDifficulty: 'easy',
    demand: 'very_high',
    noExperienceRequired: true,
  },
  {
    id: 'amazon_flex',
    title: 'Amazon Flex',
    entryRequirements: ['UK driving licence', 'Own vehicle', 'Smartphone', 'Background check'],
    flexibility: 'Book blocks that suit you — often evenings & weekends',
    hourlyPay: '£13–£18/hr equivalent',
    hourlyLow: 13,
    hourlyHigh: 18,
    skillTags: ['driving', 'general'],
    scheduleFit: ['evenings_weekends', 'flexible'],
    startSpeed: 'this_week',
    entryDifficulty: 'medium',
    demand: 'high',
  },
  {
    id: 'warehouse_weekend',
    title: 'Warehouse Weekend Shifts',
    entryRequirements: ['Right to work', 'Ability to stand/lift', 'Often no experience required'],
    flexibility: 'Weekend and night shifts widely available',
    hourlyPay: '£11–£14/hr',
    hourlyLow: 11,
    hourlyHigh: 14,
    skillTags: ['warehouse', 'general'],
    scheduleFit: ['evenings_weekends', 'flexible'],
    startSpeed: 'this_week',
    entryDifficulty: 'easy',
    demand: 'very_high',
    noExperienceRequired: true,
  },
  {
    id: 'event_staff',
    title: 'Event Staff',
    entryRequirements: ['Right to work', 'Customer-facing attitude', 'Often DBS for venues'],
    flexibility: 'Evenings, weekends, and one-off events',
    hourlyPay: '£11–£14/hr',
    hourlyLow: 11,
    hourlyHigh: 14,
    skillTags: ['hospitality', 'customer_service', 'general'],
    scheduleFit: ['evenings_weekends', 'flexible'],
    startSpeed: 'two_weeks',
    entryDifficulty: 'easy',
    demand: 'high',
    noExperienceRequired: true,
  },
  {
    id: 'matchday_steward',
    title: 'Matchday Steward',
    entryRequirements: ['Right to work', 'Training provided on site', 'Often SIA preferred'],
    flexibility: 'Match days and stadium events only',
    hourlyPay: '£11–£15/hr',
    hourlyLow: 11,
    hourlyHigh: 15,
    skillTags: ['security', 'hospitality', 'customer_service', 'general'],
    scheduleFit: ['evenings_weekends', 'flexible'],
    startSpeed: 'after_course',
    entryDifficulty: 'medium',
    demand: 'high',
  },
  {
    id: 'hospitality_weekend',
    title: 'Hospitality Weekend',
    entryRequirements: ['Right to work', 'Food hygiene helpful', 'Customer service'],
    flexibility: 'Weekends and evening service peaks',
    hourlyPay: '£11–£13/hr + tips',
    hourlyLow: 11,
    hourlyHigh: 14,
    skillTags: ['hospitality', 'customer_service', 'general'],
    scheduleFit: ['evenings_weekends', 'flexible'],
    startSpeed: 'this_week',
    entryDifficulty: 'easy',
    demand: 'very_high',
    noExperienceRequired: true,
  },
  {
    id: 'bar_staff',
    title: 'Bar Staff',
    entryRequirements: ['Right to work', 'Age 18+', 'Personal licence helpful for higher pay'],
    flexibility: 'Evenings and weekends',
    hourlyPay: '£11–£14/hr + tips',
    hourlyLow: 11,
    hourlyHigh: 14,
    skillTags: ['hospitality', 'customer_service', 'general'],
    scheduleFit: ['evenings_weekends', 'flexible'],
    startSpeed: 'this_week',
    entryDifficulty: 'easy',
    demand: 'high',
    noExperienceRequired: true,
  },
  {
    id: 'cleaner_evenings',
    title: 'Cleaner (Evenings)',
    entryRequirements: ['Right to work', 'Reliable transport', 'Often no experience required'],
    flexibility: 'Early mornings or evenings — fits around a day job',
    hourlyPay: '£11–£14/hr',
    hourlyLow: 11,
    hourlyHigh: 14,
    skillTags: ['cleaning', 'general'],
    scheduleFit: ['evenings_weekends', 'flexible', 'weekdays'],
    startSpeed: 'this_week',
    entryDifficulty: 'easy',
    demand: 'very_high',
    noExperienceRequired: true,
  },
  {
    id: 'exam_invigilator',
    title: 'Exam Invigilator',
    entryRequirements: ['Right to work', 'DBS check', 'Reliable and organised'],
    flexibility: 'Seasonal exam periods — mornings and afternoons',
    hourlyPay: '£12–£16/hr',
    hourlyLow: 12,
    hourlyHigh: 16,
    skillTags: ['administration', 'teaching', 'general'],
    scheduleFit: ['weekdays', 'flexible'],
    profiles: ['student', 'employed_part', 'not_working'],
    startSpeed: 'two_weeks',
    entryDifficulty: 'medium',
    demand: 'medium',
  },
  {
    id: 'retail_assistant',
    title: 'Retail Assistant',
    entryRequirements: ['Right to work', 'Customer service', 'Often weekend availability'],
    flexibility: 'Part-time and weekend contracts common',
    hourlyPay: '£11–£13/hr',
    hourlyLow: 11,
    hourlyHigh: 13,
    skillTags: ['retail', 'customer_service', 'sales', 'general'],
    scheduleFit: ['evenings_weekends', 'weekdays', 'flexible'],
    startSpeed: 'this_week',
    entryDifficulty: 'easy',
    demand: 'high',
    noExperienceRequired: true,
  },
  {
    id: 'seasonal_jobs',
    title: 'Seasonal Jobs',
    entryRequirements: ['Right to work', 'Availability during peak seasons'],
    flexibility: 'Christmas, summer festivals, and holiday peaks',
    hourlyPay: '£11–£15/hr',
    hourlyLow: 11,
    hourlyHigh: 15,
    skillTags: ['retail', 'hospitality', 'warehouse', 'general'],
    scheduleFit: ['evenings_weekends', 'flexible'],
    startSpeed: 'this_week',
    entryDifficulty: 'easy',
    demand: 'high',
    noExperienceRequired: true,
  },
  {
    id: 'customer_service_remote',
    title: 'Customer Service (Remote)',
    entryRequirements: ['Good English', 'Quiet workspace', 'Reliable internet'],
    flexibility: 'Shift-based; some evening/weekend remote roles',
    hourlyPay: '£11–£15/hr',
    hourlyLow: 11,
    hourlyHigh: 15,
    skillTags: ['customer_service', 'administration', 'languages', 'general'],
    scheduleFit: ['evenings_weekends', 'weekdays', 'flexible'],
    startSpeed: 'two_weeks',
    entryDifficulty: 'medium',
    demand: 'high',
  },
  {
    id: 'care_assistant',
    title: 'Care Assistant',
    hourlyPay: '£11–£14/hr',
    hourlyLow: 11,
    hourlyHigh: 14,
    flexibility: 'Days, evenings or nights depending on employer',
    entryRequirements: ['Right to work', 'DBS usually required', 'Reliable transport'],
    skillTags: ['care', 'general'],
    scheduleFit: ['weekdays', 'evenings_weekends', 'flexible'],
    startSpeed: 'two_weeks',
    entryDifficulty: 'medium',
    demand: 'very_high',
  },
  {
    id: 'dog_walking',
    title: 'Dog Walking',
    entryRequirements: ['Love of animals', 'Local clients', 'Public liability insurance recommended'],
    flexibility: 'Daytime walks — good for flexible schedules',
    hourlyPay: '£12–£18/hr',
    hourlyLow: 12,
    hourlyHigh: 18,
    skillTags: ['care', 'general'],
    scheduleFit: ['weekdays', 'flexible'],
    startSpeed: 'this_week',
    entryDifficulty: 'easy',
    demand: 'medium',
    noExperienceRequired: true,
  },
  {
    id: 'pet_sitting',
    title: 'Pet Sitting',
    entryRequirements: ['Trustworthy references', 'Local demand', 'Insurance recommended'],
    flexibility: 'Evenings, weekends, and holiday periods',
    hourlyPay: '£12–£20/visit',
    hourlyLow: 12,
    hourlyHigh: 18,
    skillTags: ['care', 'general'],
    scheduleFit: ['evenings_weekends', 'flexible'],
    startSpeed: 'two_weeks',
    entryDifficulty: 'easy',
    demand: 'medium',
    noExperienceRequired: true,
  },
  {
    id: 'mystery_shopper',
    title: 'Mystery Shopper',
    entryRequirements: ['Smartphone', 'Clear written reports', 'Right to work'],
    flexibility: 'Pick assignments that fit your schedule',
    hourlyPay: '£10–£14/hr equivalent',
    hourlyLow: 10,
    hourlyHigh: 14,
    skillTags: ['customer_service', 'writing', 'retail', 'general'],
    scheduleFit: ['evenings_weekends', 'weekdays', 'flexible'],
    startSpeed: 'this_week',
    entryDifficulty: 'easy',
    demand: 'medium',
    noExperienceRequired: true,
  },
  {
    id: 'online_tutoring',
    title: 'Online Tutoring',
    entryRequirements: ['Subject knowledge', 'DBS for under-18s', 'Quiet space and webcam'],
    flexibility: 'Evenings and weekends — set your own slots',
    hourlyPay: '£15–£30/hr',
    hourlyLow: 15,
    hourlyHigh: 30,
    skillTags: ['teaching', 'languages', 'tech'],
    scheduleFit: ['evenings_weekends', 'flexible', 'weekdays'],
    startSpeed: 'two_weeks',
    entryDifficulty: 'medium',
    demand: 'high',
  },
  {
    id: 'freelance_admin',
    title: 'Freelance Admin / VA',
    entryRequirements: ['Microsoft Office', 'Reliable internet', 'Clear communication'],
    flexibility: 'Remote and project-based',
    hourlyPay: '£12–£20/hr',
    hourlyLow: 12,
    hourlyHigh: 20,
    skillTags: ['administration', 'writing', 'customer_service'],
    scheduleFit: ['evenings_weekends', 'weekdays', 'flexible'],
    startSpeed: 'after_course',
    entryDifficulty: 'medium',
    demand: 'medium',
  },
]

type QualDef = Omit<EarningsBoostQualification, 'whyHelps'> & {
  skillTags: string[]
  hourlyBoostLow: number
  hourlyBoostHigh: number
}

export const QUALIFICATION_CATALOG: QualDef[] = [
  {
    id: 'sia_door',
    title: 'SIA Door Supervisor',
    cost: '£150–£250',
    studyTime: '4–6 days',
    averageIncrease: '+£2–£4/hr vs general hospitality',
    // Security-only — never tag as general (would hijack Retail/IT routes)
    skillTags: ['security'],
    hourlyBoostLow: 2,
    hourlyBoostHigh: 4,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'cctv',
    title: 'CCTV Licence (SIA)',
    cost: '£200–£300',
    studyTime: '3–4 days',
    averageIncrease: '+£2–£3/hr in security roles',
    skillTags: ['security'],
    hourlyBoostLow: 2,
    hourlyBoostHigh: 3,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'cscs',
    title: 'CSCS Card',
    cost: '£60–£100',
    studyTime: '1–2 days (test prep)',
    averageIncrease: 'Unlocks site work at £12–£16/hr',
    skillTags: ['trades', 'warehouse'],
    hourlyBoostLow: 1,
    hourlyBoostHigh: 3,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'forklift',
    title: 'Forklift Licence',
    cost: '£300–£500',
    studyTime: '3–5 days',
    averageIncrease: '+£2–£4/hr in warehouse roles',
    skillTags: ['warehouse'],
    hourlyBoostLow: 2,
    hourlyBoostHigh: 4,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'food_hygiene',
    title: 'Food Hygiene Certificate (Level 2)',
    cost: '£10–£25',
    studyTime: '2–4 hours online',
    averageIncrease: 'Unlocks kitchen & hospitality shifts faster',
    skillTags: ['hospitality', 'retail'],
    hourlyBoostLow: 0.5,
    hourlyBoostHigh: 1.5,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'first_aid',
    title: 'First Aid at Work',
    cost: '£100–£200',
    studyTime: '1–3 days',
    averageIncrease: 'Preferred for events, care, and security',
    skillTags: ['care', 'security', 'hospitality', 'retail', 'general'],
    hourlyBoostLow: 0.5,
    hourlyBoostHigh: 1.5,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'personal_licence',
    title: 'Personal Licence (Alcohol)',
    cost: '£100–£200',
    studyTime: '1 day + application',
    averageIncrease: '+£1–£3/hr for bar & venue roles',
    skillTags: ['hospitality'],
    hourlyBoostLow: 1,
    hourlyBoostHigh: 3,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'taxi_phv',
    title: 'Taxi / Private Hire Licence',
    cost: '£200–£400 (varies by council)',
    studyTime: '2–8 weeks (checks & tests)',
    averageIncrease: 'Unlocks £12–£20/hr driving income',
    skillTags: ['driving'],
    hourlyBoostLow: 2,
    hourlyBoostHigh: 5,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'customer_service',
    title: 'Customer Service Skills',
    cost: '£20–£80',
    studyTime: '1–2 days / online',
    averageIncrease: 'Supports retail, sales and customer-facing side roles',
    skillTags: ['retail', 'customer_service', 'sales', 'administration'],
    hourlyBoostLow: 0.5,
    hourlyBoostHigh: 2,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'ms_office',
    title: 'Microsoft Office Certification',
    cost: '£50–£150',
    studyTime: '1–4 weeks part-time',
    averageIncrease: 'Supports £12–£18/hr admin & VA work',
    skillTags: ['administration', 'writing', 'tech'],
    hourlyBoostLow: 1,
    hourlyBoostHigh: 3,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'digital_skills',
    title: 'Digital Skills Course',
    cost: '£30–£120',
    studyTime: '1–3 weeks part-time',
    averageIncrease: 'Supports digital assistant and junior IT side work',
    skillTags: ['tech', 'administration', 'marketing'],
    hourlyBoostLow: 1,
    hourlyBoostHigh: 2.5,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'english_for_work',
    title: 'English for Work',
    cost: '£20–£100',
    studyTime: '1–4 weeks part-time',
    averageIncrease: 'Supports bilingual support, tutoring and customer-facing roles',
    skillTags: ['languages', 'customer_service', 'teaching'],
    hourlyBoostLow: 0.5,
    hourlyBoostHigh: 2,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'tefl',
    title: 'TEFL / Teaching English Online',
    cost: '£50–£250',
    studyTime: '2–8 weeks part-time',
    averageIncrease: 'Unlocks online English tutoring platforms and higher tutoring rates',
    skillTags: ['teaching', 'languages'],
    hourlyBoostLow: 2,
    hourlyBoostHigh: 6,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'teaching_assistant',
    title: 'Teaching Assistant basics',
    cost: '£30–£150',
    studyTime: '1–4 weeks part-time',
    averageIncrease: 'Supports school, study support and tutoring progression',
    skillTags: ['teaching'],
    hourlyBoostLow: 1,
    hourlyBoostHigh: 3,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'care_certificate',
    title: 'Care Certificate',
    cost: '£0–£150',
    studyTime: '2–6 weeks (employer or online)',
    averageIncrease: 'Standard entry foundation for care roles',
    skillTags: ['care'],
    hourlyBoostLow: 1,
    hourlyBoostHigh: 2.5,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'safeguarding',
    title: 'Safeguarding Adults',
    cost: '£15–£60',
    studyTime: '2–6 hours online',
    averageIncrease: 'Expected by most UK care employers',
    skillTags: ['care', 'teaching'],
    hourlyBoostLow: 0.5,
    hourlyBoostHigh: 1.5,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'safeguarding_children',
    title: 'Safeguarding for working with children',
    cost: '£15–£60',
    studyTime: '2–6 hours online',
    averageIncrease: 'Expected for many tutoring and education support roles',
    skillTags: ['teaching', 'care'],
    hourlyBoostLow: 0.5,
    hourlyBoostHigh: 1.5,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'manual_handling',
    title: 'Manual Handling Awareness',
    cost: '£15–£50',
    studyTime: '2–4 hours online',
    averageIncrease: 'Common baseline for warehouse, care and site roles',
    skillTags: ['warehouse', 'care', 'trades'],
    hourlyBoostLow: 0.5,
    hourlyBoostHigh: 1.5,
    recommendedBadge: true,
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
]

type StreamDef = Omit<LongTermSideIncome, 'whyFit'>

export const LONG_TERM_CATALOG: StreamDef[] = [
  {
    id: 'freelancing',
    title: 'Freelancing (Upwork / Fiverr)',
    difficulty: 'Medium',
    startupCost: '£0–£50',
    timeToFirstIncome: '2–8 weeks',
    longTermPotential: '£500–£3,000+/month with niche skills',
    skillTags: ['writing', 'tech', 'creative', 'administration', 'marketing', 'photography'],
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'online_tutoring_lt',
    title: 'Online Tutoring Business',
    difficulty: 'Easy',
    startupCost: '£0–£30',
    timeToFirstIncome: '1–3 weeks',
    longTermPotential: '£800–£2,500/month part-time',
    skillTags: ['teaching', 'languages', 'tech'],
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'digital_products',
    title: 'Selling Digital Products',
    difficulty: 'Medium',
    startupCost: '£0–£100',
    timeToFirstIncome: '4–12 weeks',
    longTermPotential: 'Passive £200–£2,000+/month once built',
    skillTags: ['creative', 'writing', 'marketing', 'tech'],
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'etsy_pod',
    title: 'Etsy / Print on Demand',
    difficulty: 'Medium',
    startupCost: '£20–£100',
    timeToFirstIncome: '4–10 weeks',
    longTermPotential: '£200–£1,500/month with consistent listings',
    skillTags: ['creative', 'marketing', 'photography'],
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'virtual_assistant',
    title: 'Virtual Assistant',
    difficulty: 'Easy',
    startupCost: '£0–£50',
    timeToFirstIncome: '2–6 weeks',
    longTermPotential: '£600–£2,000/month part-time',
    skillTags: ['administration', 'writing', 'customer_service', 'marketing'],
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'content_creation',
    title: 'Content Creation',
    difficulty: 'Hard',
    startupCost: '£0–£200',
    timeToFirstIncome: '2–6 months',
    longTermPotential: '£300–£5,000+/month (high variance)',
    skillTags: ['creative', 'photography', 'marketing', 'writing'],
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
  {
    id: 'ai_services',
    title: 'AI Services',
    difficulty: 'Medium',
    startupCost: '£0–£50',
    timeToFirstIncome: '2–6 weeks',
    longTermPotential: '£500–£3,000/month offering AI-assisted services',
    skillTags: ['tech', 'writing', 'marketing', 'administration'],
    officialUrl: null,
    affiliateUrl: null,
    estimatedCommission: null,
    partnerBadge: false,
  },
]
